samlang-analysis/src/commonMain/kotlin/samlang/analysis/AvailableExpressionAnalysis.kt
samlang-cli/src/test/kotlin/samlang/interpreter/ExpectedResults.kt
samlang-cli/src/test/kotlin/samlang/interpreter/PrintInterpreterTest.kt
samlang-optimization/src/commonMain/kotlin/samlang/optimization/CommonSubExpressionEliminator.kt
scripts/snapshot.txt
test/runnable/cse-test-2.sam
test/runnable/cse-test-6.sam

Currently, CSE is very broken. Instead of applying an intersection over parent out edges, it does something wild:
1. Throw away expressions that could fall in intersection.
2. Instead, keep expressions that might only come from one of the parent.
Such analysis result is a recipe for unsound CSE optimization, since (2) gives a too optimistic estimation of available expressions. (although (1) is bad, it's at least harmless, we just get slightly worse code).
In this PR, I plan to first reveal the problem publicly, and then fix it in the following commits. 
Final fix:
Available expression now returns `<available expression, statement ids when it first appears>` for each statements.
CSE naively generates a replacement map based on this information. It also generates a hoisting map to compute a …

Unbreak CSE optimization

---

typescript-rewrite/samlang-core/src/interpreter/__tests__/expression-interpreter.test.ts

This PR adds the missing tests in #32 for variable scope on the `StatementBlockExpression` case. Here in the outer block we assign a variable `diffVar` to the result of the inner block containing a statement that sets variable `var` to `5n` and then retrieves that variable to assign to `diffVar` outside. We then try to retrieve `var` again using the same `variableStatement` but `var` is out of scope and we throw an error. 
On the success case, we set the variable `var` to `5n` and then retrieve it in the expression in the same block so that should pass and give us `5n`. (This is different from the test on the line above since that test doesn't use variables)

[ts-rewrite][expression-interpreter-tests] Add nested StatementBlock variable scope test

---

samlang-core/src/checker/__tests/global-typing-context-builder.test.ts
samlang-core/src/checker/global-typing-context-builder.ts
samlang-core/src/test-programs.ts

Private class support seems to be broken since it was introduced. The problem is that the private class is NOT registered in the global typing context. Therefore, when you try to use a private class within a module, it will fail. It's not caught in a test even though we have a test on private classes, because in that test we never tried to use the private classes.
In this diff, we no longer ignore private classes in global typing context. We don't need to worry about accidentally using private classes in another module, because imports of private classes are checked:
https://github.com/SamChou19815/samlang/blob/f7bade8fecd27429154b4d7d15534eef3b610b7c/samlang-core/src/checker/undefined-imports-checker.ts#L30-L33
Modified the test to include use of private classes. It still passed.

[checker] Unbreak private class type checking

---

samlang-core/src/printer/__tests__/printer-source-level.test.ts
samlang-core/src/printer/printer-source-level.ts

Resolve the TODO in #42.
See the modified test.

[printer][source-level] Special case for statement block for lift the leading `{`

---

samlang-core/src/interpreter/__tests__/expression-interpreter.test.ts

We don't really care about how the interpreter behave when the program doesn't type check, so I don't plan to add more sanity checks to interpreter now. Instead, I will just change the confusing tests.
`yarn test`

[interpreter] Fix confusing tests with arguments with wrong types given to stringToInt and intToString

---

samlang-core/src/interpreter/__tests__/module-interpreter.test.ts
samlang-core/src/interpreter/module-interpreter.ts

similar to #46, using parser to avoid writing our the AST by ourselves.
`yarn test`

[interpreter] Simplify tests for module interpreter using parser

---

samlang-core/src/__tests__/compiler-integration-test.test.ts

Thanks to @meganyin13's work on source-level interpreter, we can run it against test sources along with MIR interpreter and ASM interpreter. Since all three interpreters give the same answer, we are very confident that the interpreters and compilers are correct.
`yarn test`

[interpreter] Run samlang module interpreter in integration tests

---

samlang-core/src/ast/hir/hir-expressions.ts
samlang-core/src/compiler/mir/__tests__/mir-lowering-translator.test.ts
samlang-core/src/compiler/mir/mir-lowering-translator.ts
samlang-core/src/printer/__tests__/printer-js.test.ts
samlang-core/src/printer/printer-js.ts

According to [my roadmap](https://wiki.developersam.com/docs/oss-roadmap-2020-h2#compiler-backend) released yesterday, I plan to move as many optimizations into HIR as possible. One of such optimizations that can be easily moved is tail recursion optimization.
Tail recursion transforms a tail recursive function's body into a while loop. Currently, this is performed in MIR, where the loop in implemented by label and unconditional jumps. Currently HIR doesn't have such expressive power to describe the tail recursive call workflow.
An easy fix for the problem is to introduce while statements in HIR. If we think about it carefully, all we need is `while (true)` statement, because `while (boolExpr)` can be simulated by
```js
while (true) {
if (!boolExpr) break;
// body
}
```
I didn't introduce …

[ast][hir] Introduce while true statement to HIR

---

samlang-core/src/ast/hir/hir-expressions.ts
samlang-core/src/compiler/mir/__tests__/mir-lowering-translator.test.ts
samlang-core/src/compiler/mir/mir-lowering-translator.ts
samlang-core/src/printer/__tests__/printer-js.test.ts
samlang-core/src/printer/printer-js.ts

The HIR compiler will never generate code with `return;`. So let's remove the support and make later stages consider fewer cases.
`yarn test`

[ast][hir] Eliminate support for empty return

---

samlang-core/src/compiler/hir/__tests__/hir-move-return-coalescing.test.ts
samlang-core/src/compiler/hir/__tests__/hir-tail-recursion-transformation-hir.test.ts
samlang-core/src/compiler/hir/hir-move-return-coalescing.ts
samlang-core/src/compiler/hir/hir-tail-recursion-transformation-hir.ts

Implement the tranformation with the help of coalesceMoveAndReturnWithForHighIRStatements. It's a strict improvement over the old tailrec optimization which can't handle deep if-else blocks.
Added tests for linear flow, if-else and deep if-else test cases to test this transformation.

[compiler][hir] Implement tail recursion transformation

---

samlang-core/src/compiler/hir/__tests__/hir-eliminate-useless-ending-moves.test.ts
samlang-core/src/compiler/hir/hir-eliminate-useless-ending-moves.ts
samlang-core/src/compiler/hir/hir-move-return-coalescing.ts
samlang-core/src/compiler/hir/hir-tail-recursion-transformation-hir.ts

This is the companion version of `coalesceMoveAndReturnForHighIRStatements` for functions without a final return.
`yarn test`

[compiler][hir] Eliminate useless moves until function call from bottom

---

samlang-core/src/compiler/hir/__tests__/hir-tail-recursion-transformation-hir.test.ts
samlang-core/src/compiler/hir/hir-tail-recursion-transformation-hir.ts

Finally reached feature parity with the existing MIR compilation units
`yarn test`

[compiler][hir] Implement tailrec transformation for function both with or without returns

---

samlang-core/src/compiler/hir/__tests__/hir-tail-recursion-transformation-hir.test.ts
samlang-core/src/compiler/hir/hir-tail-recursion-transformation-hir.ts

Consider a program like
```js
function fff(n) {
if (n == 0) {
// Do nothing
} else {
fff(n - 1)
}
}
```
Without a return inserted into the true branch, the program would be:
```js
function fff(n) {
while (true) {
if (n == 0) {
// Do nothing
} else {
n = n - 1
}
}
}
```
Which will stuck in the loop forever.
`yarn test`

[compiler][hir] Insert return statement in no-transform branch of if to avoid infinite loop

---

samlang-core/src/interpreter/assembly-interpreter.ts
samlang-core/src/test-programs.ts

We can use performance test elsewhere. No need for it to slow down regular test flow.
`yarn test`

[integration-test] Eliminate unnecessarily large loops

---

samlang-core/src/printer/__tests__/printer-js.test.ts
samlang-core/src/printer/printer-js.ts

This PR improves on the previous JS printer in #39 by adding support for outputing code for builtin functions like `stringConcat`, `println`, etc as well as adding support for an entry module so the outputted code is actually runnable. These are the first two tasks in #44 .
👀 , `yarn test`, and potentially try running the outputted JS code to see that it works as expected.

Support for builtin functions and entry module for JS printer

---

samlang-core/src/printer/__tests__/printer-js.test.ts
samlang-core/src/printer/printer-js.ts

When we print `(subexpression) + (subexpression)`, we only want to print the parenthesis around the subexpressions if it is a binary expression and the operator for that subexpression has a greater or equal precedence to the operator of the whole outside expression. E.g., `1 * (3 + 4)`.
👀 , `yarn test`, and review some PEMDAS 🔢
(Aight commit history is a little weird because i tried to do amend commit and things didn't exactly work out 😅)

Avoid printing parenthesis for binary expressions whenever possible

---

samlang-core/src/compiler/hir/__tests__/hir-expression-lowering.test.ts
samlang-core/src/compiler/hir/__tests__/index.test.ts
samlang-core/src/compiler/hir/hir-expression-lowering.ts
samlang-core/src/compiler/hir/index.ts

We want to return `_this` for the HIR variable for samlang this expression because `this` is a reserved keyword.
`yarn test`

[hir] Return _this HIR variable for samlang this expression

---

samlang-core/src/printer/__tests__/printer-js.test.ts
samlang-core/src/printer/printer-js.ts

Continue the work in #71. Close #44 and fix last few indentation issues.
`yarn test`

[printer][js] Migrate all JS pretty printing to prettier framework

---

.github/workflows/ci.yml
package.json
samlang-cli/package.json
samlang-core/package.json

After changes in the last diff, type checking becomes slightly longer, but it's no longer a prereq for any other jobs. This diff completes the job separation to speed up CI.
CI

[ci] Separate out compile job to speed up CI for average cases

---

samlang-cli/package.json
yarn.lock

The new ncc works with pnp, which allows us to get rid of pnpify
CI

[cli] Adopt new ncc bundler

---

samlang-core/__tests__/compiler-integration-test.test.ts
samlang-core/analysis/__tests__/used-name-analysis.test.ts
samlang-core/analysis/used-name-analysis.ts
samlang-core/compiler/__tests__/hir-toplevel-lowering.test.ts
samlang-core/compiler/__tests__/mir-toplevel-lowering.test.ts
samlang-core/compiler/hir-toplevel-lowering.ts
samlang-core/compiler/index.ts
samlang-core/compiler/mir-toplevel-lowering.ts
samlang-core/optimization/__tests__/simple-optimizations.test.ts
samlang-core/optimization/simple-optimizations.ts
samlang-core/printer/__tests__/printer-js.test.ts
samlang-core/printer/printer-js.ts
samlang-core/services/source-processor.ts

Necessary to reduce the JS bundle size.
`yarn test`

[compiler] Move dead function elimination to source->hir compiler

---

samlang-core/printer/__tests__/printer-js.test.ts
samlang-core/printer/printer-js.ts
samlang-demo/src/__test__/index.test.ts

The interpreter mode is mostly used for internal testing. Therefore, it's defaulted to prod mode, where a println is translated to console.log and there is no `printed` accumulator.
`yarn test`

[printer][js] Create two modes for JS printer

---

samlang-core/printer/__tests__/printer-js.test.ts
samlang-core/printer/printer-js.ts
samlang-demo/src/__test__/index.test.ts

The previous implementation will produce code with syntax error when the string contains single quote. This is caught when I'm writing the integration tests for JS compiler output from samlang CLI. This diff fixes that.
`yarn test`

[printer][js] Use double quote for JS string with better escape

---

samlang-core/printer/__tests__/printer-js.test.ts
samlang-core/printer/printer-js.ts
scripts/compile-repository.js

Caught this problem when I'm finishing the integration test in `scripts/compile-repository.js`.
CI

[printer][js] Wrap div binary expression with `Math.floor` to preserve integer division semantics

---

samlang-core/ast/samlang-toplevel.ts
samlang-core/parser/__tests__/index.test.ts
samlang-core/parser/parser-class-builder.ts
samlang-core/parser/parser-module-builder.ts

This test parses the interface type. Right now no integration tests have been added for programs with interface yet, because the rest of the system still need to update the implementation to support that.
`yarn test`

[parser] Parse interface type

---

samlang-core/PL.g4
samlang-core/parser/__tests__/index.test.ts
samlang-core/parser/parser-class-builder.ts

- private stuff in interfaces don't make sense because interfaces define public APIs
- functions in interface don't make sense because interfaces are used for dynamic dispatch, and functions can only be statically dispatched.
`yarn test`

[parser] Only support parsing public methods in interfaces

---

samlang-cli/src/lsp.ts
samlang-core-services/__tests__/language-service.test.ts
samlang-core-services/language-service.ts

More work needs to be done on the printer side to respect user's choice of omitting types. Currently, it will also drop all comments.
`yarn test`

[lsp] Implement LSP command to format the entire document

---

samlang-cli/src/lsp.ts
samlang-core-services/__tests__/language-service.test.ts
samlang-core-services/language-service.ts

Related to #82 
@SamChou19815 I am a little bit struggling implementing the feature.
This is what I did:
- `samlang-cli/src/lsp.ts`: added the `connection.onFoldingRanges` handler.
- `samlang-core-services/language-service.ts`: added the `queryFoldingRange` method which should return the list of FoldingRanges.
I feel like I'm lacking in understanding of the existing codebase and my IDE doesn't feel like helping me ...
Can you give me some tips on how I can get this done ? Or some links (docs/articles...) that might help me ?
In fact, I would like to have a more general understanding of the codebase to continue contributing in the future !
I thank you in advance for your time 👍
`yarn test`

Feature: [lsp] Add folding rangs

---

samlang-core-printer/__tests__/printer-js.test.ts
samlang-core-printer/index.ts
samlang-core-printer/printer-js.ts

To be consistent with source level printer, only exposing the toString functions at `index.ts`.
`yarn test`

[printer][js] Do not expose toString methods in JS printer

---

samlang-core-compiler/hir-expression-lowering.ts
samlang-core-integration-tests/test-programs.ts
scripts/snapshot.txt
test/create-variants.sam

This is causing the bug of missing _t2!
`yarn test`

[compiler][hir] Add statements for tuple lowering

---

samlang-core-analysis/__tests__/used-name-analysis.test.ts
samlang-core-ast/hir-expressions.ts
samlang-core-compiler/__tests__/hir-eliminate-useless-ending-moves.test.ts
samlang-core-compiler/__tests__/hir-expression-lowering.test.ts
samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts
samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts
samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts
samlang-core-compiler/__tests__/mir-lowering-translator.test.ts
samlang-core-compiler/hir-expression-lowering.ts
samlang-core-compiler/hir-tail-recursion-transformation-hir.ts
samlang-core-compiler/hir-toplevel-lowering.ts
samlang-core-printer/__tests__/printer-js.test.ts

Create typed HIR for the purpose of supporting LLVM eventually.
The current types sticked into the slots are far from accurate. However, the infra is not ready yet to make them accurate. Since we don't use the types for any serious stuff, it's OK for now.
`yarn test`

[ast][compiler] Create typed HIR AST

---

samlang-core-checker/index.ts
samlang-core-services/language-service.ts

Imported module list does not give us a full picture of dependency between modules. To accurately compute the dependency, we need to use the type information.
This diff simply renames the relevant functions to remind myself that things need to be changed.
`yarn test`

[checker] Rename dependency tracker's imported module -> used module

---

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts
samlang-core-compiler/hir-expression-lowering.ts

It's necessary for SSA form for LLVM target
`yarn test`

[compiler][hir] Ensure variables in different blocks have different names

---

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts

Since we migrated to the serializable Long instead of bigint, there is no need for that.
`yarn test`

[test] Avoid serialize in HIR lowering test

---

samlang-core-ast/__tests__/hir-types.test.ts
samlang-core-ast/hir-expressions.ts
samlang-core-ast/hir-types.ts
samlang-core-compiler/__tests__/hir-expression-lowering.test.ts
samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts
samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts
samlang-core-compiler/__tests__/hir-type-lowering.test.ts
samlang-core-compiler/hir-expression-lowering.ts
samlang-core-compiler/hir-toplevel-lowering.ts
samlang-core-compiler/hir-types-lowering.ts

HIR should be able to be compiled to TS directly. Therefore, a pointer type there doesn't make sense. In addition, we know for sure that only function type and tuple type needs to be wrapped by pointer type, so we can only start to do that at LLVM transformation phase.
`yarn test`

[ast] Eliminate pointer type from HIR

---

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts
samlang-core-compiler/hir-expression-lowering.ts

The expression is pure and the value is discarded, so there is no point to record this.
`yarn test`

[compiler][hir] Do not emit wildcard assign statement

---

samlang-core-analysis/used-name-analysis.ts
samlang-core-ast/__tests__/hir-expressions.test.ts
samlang-core-ast/__tests__/hir-toplevel.test.ts
samlang-core-ast/hir-expressions.ts
samlang-core-ast/hir-toplevel.ts
samlang-core-compiler/__tests__/hir-expression-lowering.test.ts
samlang-core-compiler/__tests__/hir-string-manager.test.ts
samlang-core-compiler/__tests__/mir-lowering-translator.test.ts
samlang-core-compiler/__tests__/mir-resource-allocator.test.ts
samlang-core-compiler/__tests__/mir-toplevel-lowering.test.ts
samlang-core-compiler/hir-expression-lowering.ts
samlang-core-compiler/hir-string-manager.ts
samlang-core-compiler/hir-toplevel-lowering.ts
samlang-core-compiler/mir-lowering-translator.ts
samlang-core-compiler/mir-resource-allocator.ts
samlang-core-compiler/mir-toplevel-lowering.ts
samlang-core-printer/__tests__/printer-js.test.ts
samlang-core-printer/printer-js.ts
samlang-demo/src/__test__/index.test.ts

Further reduce the work in MIR stage and prevent duplicated code for LLVM transform.
`yarn test`

[ast][hir][compiler] Connect string constants during HIR compilation stage

---

samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts
samlang-core-compiler/hir-tail-recursion-transformation-hir.ts
samlang-core-compiler/hir-toplevel-lowering.ts

[compiler][hir] Do not call coalesceMoveAndReturnForHighIRStatements inside performTailRecursiveCallTransformationOnHighIRFunction

---

samlang-core-ast/__tests__/llvm-nodes.test.ts
samlang-core-ast/hir-types.ts
samlang-core-ast/llvm-nodes.ts
samlang-core-compiler/__tests__/hir-expression-lowering.test.ts

Make casts for explicit to help LLVM!
`yarn test`

[ast] Do not use literal type for closure

---

samlang-core-printer/__tests__/printer-js.test.ts
samlang-core-printer/printer-js.ts

Now all the sources of hoisting has been statically dealt with, there is no need to use var anymore!
`yarn test`

[printer][js] Eliminate var in JS printer

---

samlang-core-ast/__tests__/llvm-nodes.test.ts
samlang-core-ast/llvm-nodes.ts
samlang-core-compiler/llvm-lowering-translator.ts
samlang-core-interpreter/__tests__/llvm-ir-interpreter.test.ts

We needed this for == and !=
`yarn test`

[ast][llvm] Make binary statement accept operand type

---

samlang-core-ast/__tests__/llvm-nodes.test.ts
samlang-core-ast/llvm-nodes.ts

LLVM needs the special null value as placeholder for pointer typed values.
`yarn test`

[ast][llvm] Conditionally print 0 based on type

---

samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts
samlang-core-optimization/hir-common-subexpression-elimination-optimization.ts

The MIR optimization code will not be changed recently and it will eventually be removed. Therefore, let's save some time by only test it in CI.
`yarn test`

[test] Only test IR optimization interpretation in CI

---

samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts
samlang-core-optimization/__tests__/hir-inline-optimization.test.ts
samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts
samlang-core-optimization/hir-dead-code-elimination-optimization.ts
samlang-core-optimization/index.ts

Consolidate things like `b = a + 1; c = b + 2` into `c = a + 3`. When used together with DCE, this can be very powerful.
`yarn test`

[optimization] Propagate partially optimized binary expressions

---

samlang-core-ast/__tests__/hir-expressions.test.ts
samlang-core-ast/hir-expressions.ts
samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts
samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts
samlang-core-compiler/hir-expression-lowering.ts
samlang-core-compiler/llvm-lowering-translator.ts
samlang-core-optimization/__tests__/hir-common-subexpression-elimination-optimization.test.ts
samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts
samlang-core-optimization/__tests__/hir-dead-code-elimination-optimization.test.ts
samlang-core-optimization/__tests__/hir-inline-optimization.test.ts
samlang-core-optimization/__tests__/hir-local-value-numbering-optimization.test.ts
samlang-core-optimization/__tests__/hir-tail-recursion-optimization.test.ts
samlang-core-optimization/__tests__/hir-unused-name-elimination-optimization.test.ts
samlang-core-optimization/hir-common-subexpression-elimination-optimization.ts
samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts
samlang-core-optimization/hir-dead-code-elimination-optimization.ts
samlang-core-optimization/hir-inline-optimization.ts
samlang-core-optimization/hir-local-value-numbering-optimization.ts
samlang-core-optimization/hir-optimization-common.ts
samlang-core-optimization/hir-tail-recursion-optimization.ts
samlang-core-optimization/hir-unused-name-elimination-optimization.ts
samlang-core-printer/__tests__/printer-js.test.ts
samlang-core-printer/printer-js.ts

The current while AST avoids the `break` instruction, but comes with the cost of being very cumbersome. The convoluted way of producing the break condition probably will hinder future potential optimizations. Therefore, this diff aims to fix this by refactoring the AST to make break more explicit.
In this diff, I make them attached to if-else, and switch, but I will explore whether this restriction should be removed.
- `yarn test`
- `yarn test:integration`

[ast][compiler][optimization][hir] Adjust while AST

---

samlang-core-optimization/__tests__/hir-inline-optimization.test.ts
samlang-core-optimization/hir-inline-optimization.ts

Self-inlining can lead to exponential code growth. It's better to let their callsite inline a smaller function instead.
`yarn test`

[optimization] Ban self-inlining

---

samlang-cli/package.json
samlang-demo/build.js
samlang-demo/package.json
yarn.lock

With ANTLR4 finally gone, it's time to adopt esbuild for much faster bundling.
`yarn test`

[repo] Use esbuild to bundle everything

---

samlang-cli/src/lsp.ts

[lsp] Fix translation from moduleReference to URI for vscode

---

samlang-core-ast/__tests__/hir-nodes.test.ts
samlang-core-ast/hir-nodes.ts
samlang-core-ast/mir-nodes.ts
samlang-core-compiler/mir-expression-lowering.ts

The new HIR follows the following design principles:
- Same as MIR, but all type information is preserved so no casts on this level. Especially, generics are not erased at this level. This allows the later MIR level to specialize all the generics on a much closer IR.
- No optimization on this level, so nodes like while, single if, break that are introduced just for tailrec optimizations are not here.
`yarn test`

[ast][hir] Introduce all nodes for new HIR

---

samlang-core-ast/__tests__/hir-nodes.test.ts
samlang-core-ast/hir-nodes.ts
samlang-core-compiler/__tests__/hir-expression-lowering.test.ts
samlang-core-compiler/hir-expression-lowering.ts

[hir] Introduce `HIR_CLOSURE_INITIALIZATION` to preserve closure type info, but erase them in type signature

---

samlang-core-compiler/__tests__/hir-type-conversion.test.ts
samlang-core-compiler/hir-type-conversion.ts

[compiler][hir] Make `encodeHighIRNameAfterGenericsSpecialization` return name only when there are no type args

---

samlang-core-compiler/mir-toplevel-lowering.ts

[compiler][mir] Rename functions to disambiguate between `source->MIR` and `HIR->MIR`

---

samlang-core-compiler/__tests__/hir-type-conversion.test.ts
samlang-core-compiler/hir-generics-specialization.ts
samlang-core-compiler/hir-type-conversion.ts

We need to add some structural typing element here, since things might be under different generics environment before, but specialized to the same underlying structural type.
`yarn test`

[compiler][hir] Allow `solveTypeArguments` to read into the environment by `resolveIdentifierTypeMappings`

---

samlang-cli/src/cli-service.ts
samlang-core-compiler/__tests__/mir-sources-lowering.test.ts
samlang-core-compiler/mir-sources-lowering.ts
samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts
samlang-demo/src/index.ts

It should be made compatible with JS emit, although with slightly slower performance. (But since we are emitting in JS, performance is not a big issue anyways...)
`yarn test`

[compiler] Unflag reference counting feature

---

configurations/tsconfig.base.json
samlang-cli/package.json
samlang-cli/src/cli-service.ts
samlang-cli/tsconfig.json
samlang-core-compiler/__tests__/mir-sources-lowering.test.ts
samlang-core-compiler/mir-sources-lowering.ts
samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts
samlang-demo/src/index.ts
samlang-demo/tsconfig.json

After fixing the weird segfault issue due to 32-bit pointer usage, it's OK to land this again.
```
yarn test
```

[compiler] Unflag reference counting feature (again)

---

samlang-core-optimization/__tests__/mir-conditional-constant-propagation-optimization.test.ts
samlang-core-optimization/mir-conditional-constant-propagation-optimization.ts

It's a safe optimization since everything is immutable. It can reduce a lot of reliance on GC.
`yarn test`

[optimization] Treat index access as constant

---

samlang-core-ast/__tests__/mir-nodes.test.ts
samlang-core-ast/mir-nodes.ts
samlang-core-compiler/__tests__/llvm-sources-lowering.test.ts
samlang-core-compiler/__tests__/mir-sources-lowering.test.ts
samlang-core-compiler/llvm-sources-lowering.ts
samlang-core-compiler/mir-sources-lowering.ts

Close #698, and after several months, close #513. Reference counting based garbage collector is fully functional now!
```
yarn test
```

[ast][compiler] Introduce `MidIRIndexAssignStatement` to replace special-case GC instructions

---

samlang-core/__tests__/checker-integration-test.test.ts
samlang-core/checker/__tests__/global-typing-context-builder.test.ts
samlang-core/checker/global-typing-context-builder.ts
samlang-core/checker/module-type-checker.ts
samlang-core/services/__tests__/index.test.ts
samlang-core/test-programs.ts
tests/DifferentModulesDemo.sam

This diff intends to change the language design to de-specialize constructor functions. It makes them normal functions that you can use as first class values. This is intended to reduce the various similar cases in type checking into one unified case.
This diff adds them to the env first, so that collision is detected. In future diffs, I will add the runtime support and switch everything to use function call instead.
```
yarn test
```

[checker] Add constructors as normal functions to the environment

---

samlang-core/checker/__tests__/expression-type-checker.test.ts
samlang-core/checker/__tests__/global-typing-context-builder.test.ts
samlang-core/checker/__tests__/typing-context.test.ts
samlang-core/checker/global-typing-context-builder.ts
samlang-core/checker/typing-context.ts

This diff aims to provide a much stronger guarantee of what can be read from the global typing context.
```
pnpm test
```

[checker] Completely encapsulate unoptimized global context details

---

samlang-core/__tests__/checker-integration-test.test.ts
samlang-core/__tests__/errors.test.ts
samlang-core/checker/__tests__/expression-type-checker.test.ts
samlang-core/checker/expression-type-checker.ts
samlang-core/checker/module-type-checker.ts
samlang-core/checker/ssa-analysis.ts
samlang-core/checker/typing-context.ts
samlang-core/errors.ts
samlang-core/test-programs.ts

Make the context usage code even simpler.
```
pnpm test
```

[checker] Make SSA builder handle this typing

---

samlang-core/checker/__tests__/builtins.test.ts
samlang-core/checker/__tests__/global-typing-context-builder.test.ts
samlang-core/checker/__tests__/main-type-checker.test.ts
samlang-core/checker/__tests__/typing-context.test.ts
samlang-core/checker/builtins.ts
samlang-core/checker/global-typing-context-builder.ts
samlang-core/checker/main-type-checker.ts
samlang-core/checker/typing-context.ts
samlang-core/services/api.ts

Add support for validating the instantiation of an identifier type. It's not connected to production yet, but it implements all of the required checks, and it's aware of the scope of type parameters.

[checker] Type validator considering tparams in context

---

samlang-core/checker/function-call-type-checker.ts
samlang-core/test-programs.ts

Improve the completeness of implicit instantiation result with an initial synthesis pass, n rounds of iterative solving, and the final round of pinning down types.

[checker] `n+2` rounds type argument solving

---

rust-rewrite/Cargo.lock
rust-rewrite/samlang-cli/Cargo.toml
rust-rewrite/samlang-cli/src/main.rs
rust-rewrite/samlang-core/Cargo.toml
rust-rewrite/samlang-core/src/compiler.rs
samlang-core/compiler/index.ts

If users want optimized WASM, they can run it through `wasm-opt` themselves. The current optimization is powered by the same code anyways.

[rust-rewrite] Skip WASM optimization

---

.github/workflows/main.yml
.github/workflows/validate.yml

Build the binary and test during CI in two jobs, but skip the per-platform builds, since they are mostly reliable. The per-platform builds are pushed to the mainline validation stage.

[ci] Reduce CI time for PRs

---

.github/workflows/validate.yml
benchmark.sh
crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/ast/source_tests.rs
crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/global_typing_context_builder.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/ssa_analysis_tests.rs
crates/samlang-core/src/checker/undefined_imports_checker.rs
crates/samlang-core/src/compiler/hir_lowering.rs
crates/samlang-core/src/interpreter/source_interpreter.rs
crates/samlang-core/src/parser.rs
crates/samlang-core/src/parser/lexer.rs
crates/samlang-core/src/parser/lexer_test.rs
crates/samlang-core/src/parser/source_parser.rs
crates/samlang-core/src/printer/source_printer.rs
crates/samlang-core/src/services/api.rs
crates/samlang-core/src/services/location_cover.rs
crates/samlang-core/src/services/variable_definition.rs

Comments are only parsed and stored for IDE and formatting purposes. Therefore, it's better to store them as references that's managed by a module, and only leave IDs in AST nodes' slots, to avoid RC cost.
As a result of this diff, we got another 5% perf improvement

[perf] Centralize comments store

---

crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/ast/source_tests.rs

[ast][source] Add annotation nodes
This diff adds the AST nodes for annotations, which is the first step necessary to separate external annotation language and the internal type language.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/938).
* #940
* #939
* __->__ #938

[ast][source] Add annotation nodes

---

crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/ast/source_tests.rs
crates/samlang-core/src/checker.rs
crates/samlang-core/src/checker/annotation_converter.rs
crates/samlang-core/src/checker/type_.rs

[checker] Add internal type language nodes
This diff duplicates the internal type language into checker package. In the next diff, the checker package one will be the canonical internal type language.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/939).
* #940
* __->__ #939
* #938

[checker] Add internal type language nodes

---

crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/ast/source_tests.rs
crates/samlang-core/src/checker.rs
crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/checker_utils.rs
crates/samlang-core/src/checker/checker_utils_tests.rs
crates/samlang-core/src/checker/global_typing_context_builder.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/ssa_analysis.rs
crates/samlang-core/src/checker/ssa_analysis_tests.rs
crates/samlang-core/src/checker/typing_context.rs
crates/samlang-core/src/checker/typing_context_tests.rs
crates/samlang-core/src/compiler/hir_lowering.rs
crates/samlang-core/src/compiler/hir_type_conversion.rs
crates/samlang-core/src/errors.rs
crates/samlang-core/src/interpreter/source_interpreter.rs
crates/samlang-core/src/parser/source_parser.rs
crates/samlang-core/src/printer/source_printer.rs
crates/samlang-core/src/services/api.rs
crates/samlang-core/src/services/gc.rs
crates/samlang-core/src/services/location_cover.rs
crates/samlang-core/src/services/variable_definition.rs

[repo] Switch location of type related import
This diff makes the type nodes in the checker package be the canonical representation of the internal type language. All imports are updated to reflect that.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/940).
* __->__ #940

[repo] Switch location of type related import

---

crates/samlang-cli/src/main.rs
crates/samlang-core/src/checker/checker_utils.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/type_.rs
crates/samlang-core/src/common.rs
crates/samlang-core/src/compiler/wasm_lowering.rs
crates/samlang-core/src/lib.rs
crates/samlang-core/src/optimization/common_subexpression_elimination.rs
crates/samlang-core/src/optimization/conditional_constant_propagation.rs
crates/samlang-core/src/optimization/dead_code_elimination.rs
crates/samlang-core/src/optimization/optimization_common.rs
crates/samlang-core/src/parser/lexer.rs
crates/samlang-core/src/parser/source_parser.rs
sconfig.json

[perf][lexer][checker] Avoid unnecessary allocations
Lexer optimization: avoid string traversal and allocation
Checker: removed a bunch of clones
4m35s -> 3m40s: 20% pref improvement
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/943).
* __->__ #943

[perf][lexer][checker] Avoid unnecessary allocations

---

crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/checker.rs
crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/integration_tests.rs
crates/samlang-core/src/interpreter/source_interpreter.rs
crates/samlang-core/src/lib.rs
crates/samlang-core/src/services/api.rs
crates/samlang-core/src/services/gc.rs
crates/samlang-core/src/services/location_cover.rs

[checker] Non-destructive type checking
This diff makes type checking takes in a reference of parsed source, so that in the services, we can keep both.

[checker] Non-destructive type checking

---

packages/samlang-vscode/package.json
packages/samlang-vscode/src/extension.ts

[vscode] Support restarting client
This makes developing LSP much easier. No need to reload VSCode to restart language server.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/955).
* __->__ #955

[vscode] Support restarting client

---

crates/samlang-cli/src/main.rs
crates/samlang-core/src/services/api.rs
crates/samlang-wasm/src/lib.rs
crates/samlang-wasm/test-samlang-wasm.mjs

[lsp] Drop support for completion snippets
Signature help is a better alternative. In addition, this blocks auto import during completion feature.

[lsp] Drop support for completion snippets

---

.cargo/config.toml
crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/ast/source_tests.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/typing_context.rs
crates/samlang-core/src/compiler/hir_lowering.rs
crates/samlang-core/src/interpreter/source_interpreter.rs
crates/samlang-core/src/optimization/inlining_tests.rs
crates/samlang-core/src/parser/lexer.rs
crates/samlang-core/src/parser/source_parser.rs
crates/samlang-core/src/printer.rs
crates/samlang-core/src/printer/prettier.rs
crates/samlang-core/src/printer/source_printer.rs
crates/samlang-core/src/services/ast_differ.rs
crates/samlang-core/src/services/gc.rs
crates/samlang-core/src/services/server_state.rs
crates/samlang-core/src/services/variable_definition.rs

[gc] Mark string literals
Fix the embarassing crash from string literals being incorrectly GCed.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/974).
* #976
* #975
* __->__ #974
* #973

[gc] Mark string literals

---

crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/ast/source_tests.rs
crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/checker_utils.rs
crates/samlang-core/src/checker/checker_utils_tests.rs
crates/samlang-core/src/checker/global_signature.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/ssa_analysis.rs
crates/samlang-core/src/checker/type_.rs
crates/samlang-core/src/checker/typing_context.rs
crates/samlang-core/src/checker/typing_context_tests.rs
crates/samlang-core/src/compiler/hir_lowering.rs
crates/samlang-core/src/compiler/hir_type_conversion.rs
crates/samlang-core/src/interpreter/source_interpreter.rs
crates/samlang-core/src/parser.rs
crates/samlang-core/src/parser/source_parser.rs
crates/samlang-core/src/printer/source_printer.rs
crates/samlang-core/src/services/api.rs
crates/samlang-core/src/services/gc.rs
crates/samlang-core/src/services/global_searcher.rs
crates/samlang-core/src/services/location_cover.rs
crates/samlang-core/src/services/variable_definition.rs

[checker] Split id type into NominalType and GenericType
We decide whether an identifier type represents a nominal type or generic type during parse time. This allows much easier analysis in later stage of the type checking and compilation.

[checker] Split id type into NominalType and GenericType

---

crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/checker_utils.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/typing_context.rs
crates/samlang-core/src/checker/typing_context_tests.rs
crates/samlang-core/src/integration_tests.rs

This change finally makes things like `Array.reduce` able to type check. Close #980.

[checker] Introduce synthesis mode to improve completeness

---

crates/samlang-core/src/ast/wasm.rs
crates/samlang-core/src/ast/wasm_tests.rs
crates/samlang-core/src/common.rs
crates/samlang-core/src/compiler/wasm_lowering.rs
crates/samlang-core/src/integration_tests.rs
crates/samlang-core/src/libsam.wat
crates/samlang-wasm/loader.js
packages/samlang-cli/loader.js
runtime/libsam-wasm.c

Use one byte per byte instead of 4 bytes.

[compiler] Efficient string encoding

---

crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/typing_context.rs
crates/samlang-core/src/checker/typing_context_tests.rs

[checker] Resolve method type with NominalType
Prepares for eventual unification of method & function call with companion object.

[checker] Resolve method type with NominalType

---

crates/samlang-core/src/ast/hir.rs
crates/samlang-core/src/ast/hir_tests.rs
crates/samlang-core/src/ast/mir.rs
crates/samlang-core/src/ast/mir_tests.rs
crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/ast/source_tests.rs
crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/global_signature.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/ssa_analysis.rs
crates/samlang-core/src/checker/type_.rs
crates/samlang-core/src/checker/typing_context.rs
crates/samlang-core/src/checker/typing_context_tests.rs
crates/samlang-core/src/compiler/hir_generics_specialization.rs
crates/samlang-core/src/compiler/hir_lowering.rs
crates/samlang-core/src/compiler/hir_type_conversion.rs
crates/samlang-core/src/compiler/hir_type_deduplication.rs
crates/samlang-core/src/compiler/mir_lowering.rs
crates/samlang-core/src/integration_tests.rs
crates/samlang-core/src/interpreter/source_interpreter.rs
crates/samlang-core/src/optimization/unused_name_elimination.rs
crates/samlang-core/src/parser.rs
crates/samlang-core/src/parser/source_parser.rs
crates/samlang-core/src/printer/source_printer.rs
crates/samlang-core/src/services/api.rs
crates/samlang-core/src/services/gc.rs
crates/samlang-core/src/services/variable_definition.rs

In the initial support, the encoding can be inefficient. The size of the struct is equal to the max field set size + 2. We also don't offer some optimized specializations yet

[lang] Non-uniform variants initial support

---

crates/samlang-core/src/parser.rs
crates/samlang-core/src/parser/source_parser.rs

[parser] Limit max size of struct and enum
Prepare for more compact struct header encoding
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/995).
* #997
* #996
* __->__ #995

[parser] Limit max size of struct and enum

---

crates/samlang-core/src/ast/common_names.rs
crates/samlang-core/src/ast/mir.rs
crates/samlang-core/src/ast/mir_tests.rs
crates/samlang-core/src/compiler/mir_lowering.rs
crates/samlang-core/src/compiler/wasm_lowering.rs
crates/samlang-core/src/interpreter/mir_interpreter.rs

In this diff, we replace the current static inc and dec ref counting function with a very dynamic ones. With the previous restriction on struct size, we can now encode the struct header as follows:
```
| 16 bits of bitset | 16 bits of ref count |
```
where the first 16 bits encodes whether a field is a ref type. This information can then be used to help us decide at runtime whether to recursively call dec_ref function. This implementation helps to significantly reduce the code size, and helps with future integration with WASM gc as well.

[compiler][mir] Add more dynamic ref counting functions

---

crates/samlang-core/src/ast/hir.rs
crates/samlang-core/src/ast/hir_tests.rs
crates/samlang-core/src/compiler/hir_generics_specialization.rs
crates/samlang-core/src/compiler/hir_type_conversion.rs
crates/samlang-core/src/compiler/hir_type_deduplication.rs
crates/samlang-core/src/compiler/mir_lowering.rs

[refactor] Cleanup HIR primitive type
An enum is no longer needed.

[refactor] Cleanup HIR primitive type

---

crates/samlang-core/src/ast/hir.rs
crates/samlang-core/src/ast/hir_tests.rs
crates/samlang-core/src/ast/lir.rs
crates/samlang-core/src/compiler/hir_type_conversion.rs

[ast][compiler] Ban use of debug_string of HIR nodes in prod code
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1009).
* #1011
* #1010
* __->__ #1009

[ast][compiler] Ban use of debug_string of HIR nodes in prod code

---

crates/samlang-core/src/ast/hir.rs
crates/samlang-core/src/ast/hir_tests.rs
crates/samlang-core/src/common.rs
crates/samlang-core/src/compiler/hir_lowering.rs
crates/samlang-core/src/compiler/mir_generics_specialization.rs

These specialization enum constructor and destructor are introduced. They serve to preserve in structure in HIR, and in MIR, they should be transformed to lower level struct init and casts. In the future, we will make use of these information to emit specialized enum representations like those described in #999

[ast][hir] Introduce `ConditionalDestructure` and `EnumInit`

---

crates/samlang-core/src/compiler/lir_lowering.rs

[compiler][lir] Also consider odd ints as non-pointers
This change can give us a lot of freedom for enums. We are no longer limited to a small enum set, as long as we make all enum tags odd ints.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1016).
* #1017
* __->__ #1016

[compiler][lir] Also consider odd ints as non-pointers

---

crates/samlang-core/src/compiler/lir_lowering.rs
crates/samlang-core/src/compiler/mir_generics_specialization.rs

[compiler][mir] Make sure all enum tags are odd integers
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1017).
* __->__ #1017
* #1016

[compiler][mir] Make sure all enum tags are odd integers

---

crates/samlang-core/src/checker.rs
crates/samlang-core/src/checker/type_system.rs

This diff adds the foundation of a new modularized type system implementation, connected to a stacked error and pretty error printing infra. We are able to print the new stacked error in isolated tests now, although it's still not connected to the rest of the system.

[checker] New type system implementation

---

crates/samlang-core/src/checker/checker_utils.rs
crates/samlang-core/src/checker/checker_utils_tests.rs
crates/samlang-core/src/checker/global_signature.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/type_system.rs
crates/samlang-core/src/checker/typing_context.rs

[checker][refactor] Move type subst helper into type_system module
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1040).
* #1041
* __->__ #1040

[checker][refactor] Move type subst helper into type_system module

---

crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/main_checker.rs

Makes accidental use of hints that contain placeholders impossible.
Close #1024.

[checker] Migrate to type hint with better usage enforcements

---

crates/samlang-core/src/ast/reason.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/type_.rs
crates/samlang-core/src/errors.rs

[checker] Remove need to use heap for type parameter mismatch errors
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1045).
* #1047
* #1046
* __->__ #1045

[checker] Remove need to use heap for type parameter mismatch errors

---

crates/samlang-core/src/compiler/lir_lowering.rs
crates/samlang-core/src/parser/source_parser.rs
crates/samlang-heap/src/lib.rs

[refactor] Eliminate all `Heap.alloc_str_permanent`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1061).
* #1062
* __->__ #1061

[refactor] Eliminate all `Heap.alloc_str_permanent`

---

crates/samlang-core/src/compiler/lir_lowering.rs
crates/samlang-core/src/integration_tests.rs
crates/samlang-core/src/parser/source_parser.rs
crates/samlang-core/src/services/location_cover.rs
crates/samlang-heap/src/lib.rs

[tests] Speed up some tests
- Early contains position check to speed up location_cover test
- Only do the search on mostly hopeful locations by inspecting the source line by line
- Remove redundant checking in formatter tests
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1062).
* __->__ #1062
* #1061

[tests] Speed up some tests

---

crates/samlang-collections/src/local_stacked_context.rs
crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/ast/source_tests.rs
crates/samlang-core/src/compiler/hir_lowering.rs
crates/samlang-core/src/compiler/lir_lowering.rs
crates/samlang-core/src/compiler/mir_generics_specialization.rs
crates/samlang-core/src/optimization/inlining_tests.rs
crates/samlang-core/src/services/api.rs
crates/samlang-core/src/services/api_tests.rs
crates/samlang-heap/src/lib.rs

[heap][string] 16 byte wide PStr
This will allow us to include more strings into small string optimization, which doesn't have to go through the string interning pool. It introduces a 5% regression up front, but I believe it will pay off in a multithreading world.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1099).
* #1100
* __->__ #1099
* #1098

[heap][string] 16 byte wide PStr

---

crates/samlang-core/src/printer/source_printer.rs

[printer] Do not print `()` after variant pattern with no attached data
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1107).
* #1108
* __->__ #1107

[printer] Do not print `()` after variant pattern with no attached data

---

crates/samlang-core/src/compiler/mir_generics_specialization.rs
crates/samlang-core/src/integration_tests.rs
crates/samlang-core/src/interpreter.rs
crates/samlang-core/src/printer/source_printer.rs

[compiler][mir] Do not optimize enums as unboxed
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1108).
* __->__ #1108
* #1107

[compiler][mir] Do not optimize enums as unboxed

---

crates/samlang-core/src/ast/lir.rs
crates/samlang-core/src/ast/lir_tests.rs
crates/samlang-core/src/compiler/lir_lowering.rs

[ast][lir] Fix late init declaration pretty printing
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1109).
* #1110
* __->__ #1109

[ast][lir] Fix late init declaration pretty printing

---

crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/ast/source_tests.rs
crates/samlang-core/src/compiler/mir_generics_specialization.rs

[compiler][mir] Handle SingleIf in generics specialization
It might be a possible instruction to encounter once we add if let compilation support.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1112).
* __->__ #1112
* #1111

[compiler][mir] Handle SingleIf in generics specialization

---

crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/errors.rs
crates/samlang-core/src/integration_tests.rs
crates/samlang-core/src/services/api_tests.rs
crates/samlang-core/src/services/server_state.rs

[errors] Tweak some error names and messages

[errors] Tweak some error names and messages

---

crates/samlang-core/src/checker/pattern_matching.rs

[checker][pattern-matching] Add `nothing` as a convenience factory function
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1117).
* #1118
* __->__ #1117

[checker][pattern-matching] Add `nothing` as a convenience factory function

---

crates/samlang-core/src/checker/pattern_matching.rs

[checker][pattern-matching] Take context by reference
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1118).
* __->__ #1118
* #1117

[checker][pattern-matching] Take context by reference

---

crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/type_.rs
crates/samlang-core/src/checker/typing_context.rs
crates/samlang-core/src/errors.rs
crates/samlang-core/src/services/global_searcher.rs
crates/samlang-core/src/services/location_cover.rs

[checker] Ban irrefutable patterns in `if let`

[checker] Ban irrefutable patterns in `if let`

---

crates/samlang-core/src/services/api.rs
crates/samlang-core/src/services/api_tests.rs
crates/samlang-core/src/services/location_cover.rs

[ide] Do not return hover type results for arbitrary expressions
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1121).
* #1125
* #1124
* #1123
* #1122
* __->__ #1121

[ide] Do not return hover type results for arbitrary expressions

---

crates/samlang-core/src/ast/source.rs
crates/samlang-core/src/ast/source_tests.rs
crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/ssa_analysis.rs
crates/samlang-core/src/checker/typing_context.rs
crates/samlang-core/src/checker/typing_context_tests.rs
crates/samlang-core/src/compiler/hir_lowering.rs
crates/samlang-core/src/errors.rs
crates/samlang-core/src/optimization/loop_invariant_code_motion.rs
crates/samlang-core/src/parser/source_parser.rs
crates/samlang-core/src/printer/source_printer.rs
crates/samlang-core/src/services/gc.rs
crates/samlang-core/src/services/global_searcher.rs
crates/samlang-core/src/services/variable_definition.rs
tests/SortableList.sam

[lang] Deeply nested pattern matching

[lang] Deeply nested pattern matching

---

crates/samlang-core/src/ast/loc.rs
crates/samlang-core/src/ast/source.rs

[ast][cleanup][EZ] Do not make pattern polymorphic over base
This is a sharing strategy added when we have both destructuring and matching pattern. Now we only have matching pattern, so this kind of extra indirection is no longer necessary.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1129).
* __->__ #1129
* #1128

[ast][cleanup][EZ] Do not make pattern polymorphic over base

---

crates/samlang-core/src/checker/checker_tests.rs
crates/samlang-core/src/checker/global_signature.rs
crates/samlang-core/src/checker/main_checker.rs
crates/samlang-core/src/checker/type_system.rs
crates/samlang-core/src/checker/typing_context_tests.rs
crates/samlang-core/src/errors.rs
crates/samlang-core/src/integration_tests.rs
crates/samlang-core/src/parser.rs
crates/samlang-core/src/printer/source_printer.rs
crates/samlang-core/src/services/location_cover.rs
crates/samlang-core/src/services/server_state.rs

[refactor][errors] Expose less structs from errors
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1131).
* #1132
* __->__ #1131

[refactor][errors] Expose less structs from errors

---

crates/samlang-checker/src/typing_context.rs

[checker] Add missing substitution during conformance check
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1143).
* __->__ #1143
* #1142

[checker] Add missing substitution during conformance check

---

crates/samlang-printer/src/source_printer.rs
crates/samlang-services/src/ast_differ.rs
crates/samlang-services/src/variable_definition.rs
tests/SortableList.sam

[printer] Always print `{}` even if the toplevel members are empty

[printer] Always print `{}` even if the toplevel members are empty

---

crates/samlang-compiler/src/lib.rs
crates/samlang-compiler/src/lir_lowering.rs
crates/samlang-compiler/src/lir_unused_name_elimination.rs
crates/samlang-compiler/src/wasm_lowering.rs

[compiler] Rename some functions with incorrect AST phase names

[compiler] Rename some functions with incorrect AST phase names

---

crates/samlang-ast/src/mir.rs
crates/samlang-ast/src/wasm.rs
crates/samlang-compiler/src/hir_lowering.rs
crates/samlang-compiler/src/hir_string_manager.rs
crates/samlang-compiler/src/lir_lowering.rs
crates/samlang-compiler/src/mir_constant_param_elimination.rs
crates/samlang-compiler/src/mir_generics_specialization.rs
crates/samlang-compiler/src/wasm_lowering.rs

[compiler] Fix invalid type parameter list
We should not sort parameter list, but instead always following the order of class tparams + function tparams. Otherwise, we will get inconsistent types and mess up GC.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1159).
* #1163
* #1162
* #1161
* #1160
* __->__ #1159

[compiler] Fix invalid type parameter list

---

crates/samlang-ast/src/mir.rs
crates/samlang-ast/src/wasm.rs
crates/samlang-checker/src/pattern_matching.rs
crates/samlang-compiler/src/hir_lowering.rs
crates/samlang-compiler/src/hir_string_manager.rs
crates/samlang-compiler/src/lir_lowering.rs
crates/samlang-compiler/src/mir_constant_param_elimination.rs
crates/samlang-compiler/src/mir_generics_specialization.rs
crates/samlang-compiler/src/wasm_lowering.rs
crates/samlang-parser/src/lib.rs
crates/samlang-parser/src/source_parser.rs
crates/samlang-services/src/location_cover.rs
packages/samlang-website/src/components/samlang-wasm-glue.js
std/set.sam
tests/AllTests.sam
tests/MapTests.sam
tests/SetTests.sam
tests/snapshot.txt

[parser] Reorganize source parser code into smaller inline mods
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1163).
* __->__ #1163
* #1162
* #1161
* #1160
* #1159

[parser] Reorganize source parser code into smaller inline mods

---

crates/samlang-ast/src/source.rs
crates/samlang-ast/src/source_tests.rs
crates/samlang-checker/src/checker_integration_tests.rs
crates/samlang-checker/src/checker_tests.rs
crates/samlang-checker/src/global_signature.rs
crates/samlang-checker/src/main_checker.rs
crates/samlang-checker/src/ssa_analysis.rs
crates/samlang-checker/src/ssa_analysis_tests.rs
crates/samlang-checker/src/type_.rs
crates/samlang-compiler/src/hir_lowering.rs
crates/samlang-compiler/src/hir_type_conversion.rs
crates/samlang-parser/src/lib.rs
crates/samlang-parser/src/source_parser.rs
crates/samlang-printer/src/source_printer.rs
crates/samlang-services/src/api_tests.rs
crates/samlang-services/src/ast_differ.rs
crates/samlang-services/src/gc.rs
crates/samlang-services/src/global_searcher.rs
crates/samlang-services/src/lib.rs
crates/samlang-services/src/location_cover.rs
crates/samlang-services/src/variable_definition.rs

[parser][printer] Consistent comment attachment and printing for classes and interfaces
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1168).
* #1170
* #1169
* __->__ #1168

[parser][printer] Consistent comment attachment and printing for classes and interfaces

---

crates/samlang-ast/src/source.rs
crates/samlang-ast/src/source_tests.rs
crates/samlang-parser/src/source_parser.rs
crates/samlang-printer/src/lib.rs
crates/samlang-printer/src/source_printer.rs
crates/samlang-services/src/ast_differ.rs
crates/samlang-services/src/lib.rs

[parser][printer] Consistent comment attachment and printing for toplevels
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1169).
* #1170
* __->__ #1169

[parser][printer] Consistent comment attachment and printing for toplevels

---

crates/samlang-ast/src/lib.rs
crates/samlang-compiler/src/mir_generics_specialization.rs

[compiler] Document all casts during generics specialization
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1187).
* #1188
* __->__ #1187
* #1186

[compiler] Document all casts during generics specialization

---

crates/samlang-ast/src/hir.rs
crates/samlang-ast/src/hir_tests.rs
crates/samlang-ast/src/lir.rs
crates/samlang-ast/src/lir_tests.rs
crates/samlang-ast/src/mir.rs
crates/samlang-ast/src/mir_tests.rs
crates/samlang-compiler/src/hir_lowering.rs
crates/samlang-compiler/src/hir_string_manager.rs
crates/samlang-compiler/src/lir_lowering.rs
crates/samlang-compiler/src/lir_unused_name_elimination.rs
crates/samlang-compiler/src/mir_constant_param_elimination.rs
crates/samlang-compiler/src/mir_generics_specialization.rs
crates/samlang-compiler/src/wasm_lowering.rs
crates/samlang-optimization/src/unused_name_elimination.rs

[hir][refactor] Simpler global string representation
We can use the Heap PStr uniqueness guarantee to simplify representation, and avoiding generating all these strings that might be GCed anyways.

[hir][refactor] Simpler global string representation

---

crates/samlang-ast/src/lir.rs
crates/samlang-ast/src/lir_tests.rs
crates/samlang-ast/src/mir.rs
crates/samlang-ast/src/mir_tests.rs
crates/samlang-compiler/src/lir_lowering.rs
crates/samlang-compiler/src/mir_generics_specialization.rs
crates/samlang-compiler/src/mir_type_deduplication.rs

[ast][ir] Introduce AnyPointer IR type
This is intended to mirror the any type in the WASM GC spec.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1207).
* #1208
* __->__ #1207

[ast][ir] Introduce AnyPointer IR type

---

crates/samlang-ast/src/lir.rs
crates/samlang-ast/src/lir_tests.rs
crates/samlang-ast/src/mir.rs
crates/samlang-ast/src/mir_tests.rs
crates/samlang-compiler/src/lir_lowering.rs
crates/samlang-compiler/src/mir_constant_param_elimination.rs
crates/samlang-compiler/src/mir_generics_specialization.rs
crates/samlang-compiler/src/mir_type_deduplication.rs
crates/samlang-compiler/src/wasm_lowering.rs
crates/samlang-optimization/src/unused_name_elimination.rs

[compiler] Make use of i31 literals
Make the optimized form of variant actually i31 without assuming the representation during generics specialization. Then we do the `i * 2 + 1` conversion during LIR printing and wasm lowering. Eventually, the WASM one will be replaced by the actual WASM i31.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1208).
* __->__ #1208
* #1207

[compiler] Make use of i31 literals

---

Cargo.lock
crates/samlang-wasm/Cargo.toml

The current version won't work for future Rust versions.

[wasm] Bump wasm-bindgen

---

crates/samlang-ast/src/hir.rs
crates/samlang-ast/src/hir_tests.rs
crates/samlang-compiler/src/hir_lowering.rs
crates/samlang-compiler/src/hir_type_conversion.rs
crates/samlang-compiler/src/mir_generics_specialization.rs

It will be used to model the class id reference.

[ast][ir] Introduce i31 type and `0 as i31` in HIR

---

crates/samlang-ast/src/wasm.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1234).
* #1237
* #1236
* #1235
* __->__ #1234

[wasm][ast] Support `ref.cast` instruction

---

crates/samlang-ast/src/lir.rs
crates/samlang-ast/src/wasm.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1235).
* #1237
* #1236
* __->__ #1235
* #1234

[wasm][ast] Store lir::Type instead of String in wasm ast
