SamChou19815/samlang

src/main/kotlin/samlang/checker/CheckedExprTypeFixer.kt, src/main/kotlin/samlang/checker/ConstraintAwareTypeChecker.kt, src/test/resources/samlang/programs/good-various_syntax_forms.samlang
=> Add more tests (Fix #3)

typescript-rewrite/samlang-core/src/interpreter/__tests__/expression-interpreter.test.ts, typescript-rewrite/samlang-core/src/interpreter/__tests__/module-interpreter.test.ts, typescript-rewrite/samlang-core/src/interpreter/expression-interpreter.ts, typescript-rewrite/samlang-core/src/interpreter/module-interpreter.ts
Part 2 of #28 
(Still have to write tests)
=> [ts-rewrite][module-interpreter] Implement Module Interpreter

samlang-core/src/printer/__tests__/printer-prettier-core.test.ts, samlang-core/src/printer/printer-prettier-core.ts
The prettier paper: https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf
=> [printer] Implement prettier algorithm according to prettier paper

samlang-core/src/printer/__tests__/printer-prettier-core.test.ts, samlang-core/src/printer/printer-prettier-core.ts
The semantics of the construst is already documented in the code, so I will not repeat it here. Addition of this construct is necessary to get a nicer looking output in the following scanario:
Suppose we want to pretty print a list. When we have enough space, we can print it like:
```
[a, b, c, d, e, f]
```
When we don't have enough space, we can indent the elements in the list like:
```
[
a,
b,
c,
d,
e,
f
]
```
In the prettier core algorithm, the conditional space or indentation is represented by the `LINE` document. However, the `LINE` document always flattens to a space. Therefore, in the flatten output, we will actually get:
```
[ a, b, c, d, e, f ]
```
, which isn't what we expect.
See the modified test. Now it no longer prints extra whitespaces.
=> [printer][prettier] Implement `LINE_FLATTEN_TO_NIL` as a prettier extension

samlang-core/src/interpreter/__tests__/expression-interpreter.test.ts, samlang-core/src/interpreter/expression-interpreter.ts
Using parser to construct source-level AST for us, so that we don't have to construct them by hand. It results in a much cleaner test file.
This rewrite helps us to spot two problems easily:
- The implementation for stringToInt and intToString seems to be off.
- Inside the interpreter, we forget to pass around context. (fixed in this diff)
See the modified tests.
=> [interpreter] Cleaner expression interpreter test

package.json, samlang-core/src/checker/expression-type-checker.ts, yarn.lock
Use my latest linter config without airbnb.
`yarn lint`
=> [linter] Adopt new linter config

samlang-core/src/compiler/hir/__tests__/index.test.ts
We can use this test result to guide implementation of tailrec optimizations in HIR.
`yarn test`
=> [compiler][hir] Add a unit test on compiling factorial function

samlang-core/src/compiler/hir/__tests__/hir-move-return-coalescing.test.ts, samlang-core/src/compiler/hir/hir-move-return-coalescing.ts
See the jsdoc for its rationale and usage
`yarn test`
=> [compiler][hir] Implement move-return coalescing

samlang-core/src/compiler/hir/__tests__/index.test.ts
To guide implementation for tailrec in this case
`yarn test`
=> [compiler][hir] Add a test on tailrec transformable function without return

samlang-cli/src/cli/__tests__/index.test.ts, samlang-core/src/analysis/used-name-analysis.ts, samlang-core/src/optimization/common-subexpression-elimination-optimization.ts
=> [linter] Remove dead eslint suppression comments

package.json, samlang-cli/package.json, samlang-core/package.json, samlang-core/src/parser/parser-class-builder.ts, samlang-core/src/parser/parser-expression-builder.ts, samlang-core/src/parser/parser-module-builder.ts, samlang-core/src/parser/parser-pattern-builder.ts, samlang-core/src/parser/parser-statement-block-builder.ts, samlang-core/suppress-type-errors.js, yarn.lock
=> [dependency] Bump dependencies

samlang-core/src/printer/__tests__/printer-js.test.ts, samlang-core/src/printer/printer-js.ts, samlang-core/src/printer/printer-prettier-library.ts, samlang-core/src/printer/printer-source-level.ts
Updated existing test. You can see nicer indentation.
=> Pretty-print JS with prettier

.eslintignore, .gitignore, .prettierignore, samlang-cli/package.json, samlang-cli/tsconfig.json
Allow us to optimize some CI workflows.
CI
=> [cli] Bundle without compile to JS

.github/workflows/integration-test.yml
Nice to have, and it also gives us some linux runtime library to play with.
CI
=> [ci] Create release artifact if it passes all integration test

package.json, samlang-core/index.ts, samlang-core/printer/index.ts, samlang-demo/package.json, samlang-demo/src/__test__/index.test.ts, samlang-demo/src/index.ts, samlang-demo/tsconfig.json, scripts/compile-runtime, workspaces.json, yarn.lock
Make a new demo package based on samlang in TS.
CI
=> [demo] Setup demo package

samlang-cli/package.json, samlang-cli/src/lsp.ts
Move deps to dev-dependencies since we already bundle everything
Test in prod
=> [cli] Adjust samlang-cli to make it shippable on npm

samlang-core/ast/hir-expressions.ts, samlang-core/compiler/__tests__/mir-lowering-translator.test.ts, samlang-core/compiler/mir-lowering-translator.ts, samlang-core/printer/__tests__/printer-js.test.ts, samlang-core/printer/printer-js.ts
This is important to shift more optimization to HIR.
CI
=> [ast][hir] Make HighIRFunctionCallStatement have optional return collector

samlang-core/index.ts, samlang-core/printer/index.ts, samlang-demo/src/__test__/index.test.ts, samlang-demo/src/index.ts
Let's make @meganyin13's contribution of JS printer onto the samlang demo eventually.
`yarn test`
=> [demo] Show JS compiler output in demo package

samlang-cli/src/cli-service.ts, samlang-cli/src/index.ts
=> [cli] Emit JS in CLI compile command as well

samlang-demo/build.js, samlang-demo/package.json
ANTLR4 requires those modules. Without stubbing, it will crash.
Tested in prod.
=> [demo] Stub assert and util in bundled demo

vscode/package.json
=> [vscode] Bump version to prepare for publishing

samlang-cli/package.json, samlang-demo/package.json
The new release contains no actual changes. I only bumped the version number to make it consistent with an upcoming release's version number.
=> [repo] Publish demo and cli package as 0.3.0

.eslintignore, .gitignore, .prettierignore
It can be safely generated by yarn plugin with no overhead. No need to check it in.
CI
=> gitignore workspaces.json

.github/workflows/integration-test.yml, package.json, scripts/compile-repository.ts, yarn.lock
> Everything written in JS will be eventually rewritten in TS.
> - dev-sam
CI
=> [test] Convert the integration test script to TS

.github/workflows/tssa-analysis.yml, package.json, yarn.lock
It's helpful to use the dependency graph analysis result to decide whether everything is properly tested.
CI
=> [repo] Adopt TSSA for static analysis

.gitignore
To be consistent with website repo, purge the file that can be effortlessly regenerated in CI.
CI
=> [repo] Purge workspaces.json

configurations/latest-local-linter-config.js, package.json
=> [repo] Added script to test latest linter config from website repo locally

.github/PULL_REQUEST_TEMPLATE.md
=> [repo] Modify PR template to give it a good default for most cases

samlang-cli/src/lsp.ts, samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
Currently it only supports goto definition for functions and methods.
`yarn test`
=> [lsp] Implement basic support for goto definition command

samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
=> [lsp] Implement support for goto class definition

samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
=> [lsp] Support goto constructor definition

samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
=> [lsp] Implement goto local variable definition support

samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/package.json, workspaces.json, yarn.lock
One less item in the dependency chain.
`yarn test`
=> [printer][test] Remove tests's dependency on samlang-core-service

samlang-cli/src/cli-service.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/index.ts, samlang-core-printer/printer-js.ts, samlang-demo/src/index.ts
Make it more consistent with source-level printer
`yarn test`
=> [printer][js] Do not hardcode availableWidth

samlang-core-printer/printer-prettier-core.ts
Help @meganyin13 with optional devsesh.
`yarn test`
=> [prettier][core] Add more documentation

samlang-cli/package.json, samlang-demo/package.json
=> [repo] Publish 0.3.1

.vscode/settings.json
=> [repo] Use local samlang program path

samlang-cli/src/cli/__tests__/cli-parser.test.ts, samlang-cli/src/cli/__tests__/index.test.ts, samlang-cli/src/cli/cli-parser.ts, samlang-cli/src/cli/index.ts, samlang-cli/src/index.ts, samlang-core-services/__tests__/source-processor.test.ts, samlang-core-services/index.ts, samlang-core-services/source-processor.ts
We exposed format command in LSP, so we should also expose it in CLI.
`yarn test`
=> [cli] Introduce format command

samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-printer/printer-source-level.ts, test/cse-test-3.sam, test/if-else-consistency.sam, test/if-else-unreachable-1.sam, test/if-else-unreachable-2.sam, test/math-functions.sam
=> [printer] Specialize for chained if-else

package.json
=> [repo] Ensure samlang code in repo is consistently formatted

.github/workflows/llvm-migration.yml, .gitignore, runtime/Makefile
Trying to setup LLVM runtime by compiling the runtime to llvm bitcode, so that it can be later linked with another llvm program.
CI
=> [runtime] Setup llvm runtime

samlang-core-checker/module-type-checker.ts, samlang-core-checker/typing-context.ts
=> [checker] Improve type annotations for typing contexts

samlang-core-checker/__tests/expression-type-checker.test.ts, samlang-core-checker/__tests/global-typing-context-builder.test.ts, samlang-core-checker/__tests/index.test.ts, samlang-core-checker/__tests/statement-type-checker.test.ts, samlang-core-checker/__tests/type-validator.test.ts, samlang-core-checker/__tests/typing-context.test.ts, samlang-core-checker/expression-type-checker.ts, samlang-core-checker/global-typing-context-builder.ts, samlang-core-checker/index.ts, samlang-core-checker/module-type-checker.ts, samlang-core-checker/type-validator.ts, samlang-core-checker/typing-context.ts, samlang-core-services/language-service.ts
=> [checker] Use resolved type identifier for type checking

samlang-core-ast/samlang-expressions.ts, samlang-core-checker/expression-type-checker.ts, samlang-core-checker/typing-context.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-interpreter/source-level-interpreter.ts, samlang-core-parser/parser-expression-builder.ts, samlang-core-printer/printer-source-level.ts
=> [ast][checker] Record type of data variable in match expression

samlang-core-analysis/__tests__/used-name-analysis.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-eliminate-useless-ending-moves.test.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts, samlang-core-compiler/__tests__/mir-lowering-translator.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-printer/__tests__/printer-js.test.ts
=> [ast] Ensure that HIR_BINARY always have type int

samlang-core-checker/typing-context.ts
=> [checker] Factor out getClassTypeInformation in typing-context

.github/workflows/ci-runtime.yml, runtime/Makefile
=> [runtime] Link bitcode together instead of object code

.github/workflows/ci-runtime.yml
=> [ci][runtime] Stop caching LLVM

samlang-core-ast/llvm-nodes.ts
=> [ast] Added typedef for LLVM types

scripts/snapshot.txt, test/if-else-same-variable-name.sam
=> [test] Add an integration test to confirm nested block names are properly renamed

samlang-core-analysis/__tests__/used-name-analysis.test.ts, samlang-core-analysis/used-name-analysis.ts, samlang-core-ast/hir-toplevel.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/__tests__/mir-toplevel-lowering.test.ts, samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-printer/__tests__/printer-js.test.ts
=> [compiler][hir] Produce generic type erased type def

samlang-core-checker/__tests/expression-type-checker.test.ts
=> [test][checker] Avoid writing range in checker test

samlang-core-ast/common-nodes.ts, samlang-core-compiler/__tests__/hir-type-lowering.test.ts, samlang-core-compiler/hir-types-lowering.ts
=> [compiler][hir] Setup HIR type lowering

samlang-core-ast/hir-toplevel.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/hir-toplevel-lowering.ts
=> [ast][hir][compiler] Make HIR type definition using lowered HIR type

samlang-core-ast/hir-expressions.ts, samlang-core-ast/hir-toplevel.ts, samlang-core-ast/hir-types.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-tail-recursion-transformation-hir.ts, samlang-core-compiler/hir-toplevel-lowering.ts
=> [ast][hir][compiler] Lower HIR with HIR types

samlang-core-printer/__tests__/printer-js.test.ts
=> [printer][test] Fix printer-js test type errors

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/__tests__/hir-toplevel.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-ast/hir-toplevel.ts
=> [ast][hir] Create debug printer functions for later testing

samlang-core-analysis/__tests__/used-name-analysis.test.ts, samlang-core-compiler/__tests__/hir-eliminate-useless-ending-moves.test.ts, samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts
=> [test] Use debugPrinter for HIR to simplify some test writing

samlang-core-ast/hir-types.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts
=> [test] Use debugPrinter for HIR to simplify HIR lowering test writing

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-eliminate-useless-ending-moves.test.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/__tests__/mir-lowering-translator.test.ts, samlang-core-compiler/__tests__/mir-toplevel-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-tail-recursion-transformation-hir.ts, samlang-core-compiler/mir-lowering-translator.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts, samlang-demo/src/__test__/index.test.ts
We need this type info for LLVM.
`yarn test`
=> [ast][hir][compiler] Make function call return collector typed

runtime/libsam/example.ll
=> [runtime] Make everything in runtime example named

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Emit throw when going into an unreachable branch

.github/workflows/integration-test.yml
=> [ci] Make integration test run on ubuntu again

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-eliminate-useless-ending-moves.test.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-tail-recursion-transformation-hir.ts
=> [ast][hir][compiler] Record phi variables in HIR if-else

samlang-core-analysis/__tests__/used-name-analysis.test.ts, samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/__tests__/mir-lowering-translator.test.ts, samlang-core-compiler/hir-tail-recursion-transformation-hir.ts, samlang-core-printer/__tests__/printer-js.test.ts
=> [ast][compiler][hir] Record phi variables in HIR while

samlang-core-ast/hir-expressions.ts, samlang-core-ast/hir-types.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-types-lowering.ts
The LLVM IR needs it.
`yarn test`
=> [ast][compiler][hir] Retain bool type in HIR

samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/hir-types.ts, samlang-core-ast/llvm-nodes.ts
=> [ast] Setup LLVM type nodes

samlang-core-ast/llvm-nodes.ts
=> [ast][llvm] Setup typedef of LLVM instructions

runtime/libsam/example.ll
=> [runtime][example] Update example with closure like manipulation

samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts
=> [ast][llvm] Setup LLVM value constructors and pretty printers

samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts
=> [ast][llvm] Setup LLVM instructions constructors and pretty printers

samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts
=> [ast][llvm] Add support for jump instruction

runtime/libsam/example.ll, samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts
=> [ast][llvm] Fix typedef for all LLVM nodes

samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts
=> [ast][llvm] Add bitcast instruction

runtime/libsam/example.ll, samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts
=> [ast][llvm] Setup LLVM toplevel AST

.yarn/sdks/eslint/lib/api.js, .yarn/sdks/eslint/package.json, .yarn/sdks/prettier/index.js, .yarn/sdks/prettier/package.json, .yarn/sdks/typescript/lib/tsc.js, .yarn/sdks/typescript/lib/tsserver.js, .yarn/sdks/typescript/lib/typescript.js, .yarn/sdks/typescript/package.json
=> [repo][vscode] Update pnpify

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Avoid passing around void value in function call

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [hir][compiler] Avoid producing void values for phi

samlang-core-analysis/__tests__/live-variable-analysis.test.ts, samlang-core-analysis/live-variable-analysis.ts, samlang-core-ast/__tests__/mir-nodes.test.ts, samlang-core-ast/mir-nodes.ts, samlang-core-compiler/__tests__/asm-toplevel-generator.test.ts, samlang-core-compiler/asm-register-allocator.ts, samlang-core-compiler/asm-toplevel-generator.ts, samlang-core-compiler/mir-toplevel-lowering.ts, samlang-core-interpreter/__tests__/mid-ir-interpreter.test.ts, samlang-core-optimization/__tests__/index.test.ts, samlang-core-optimization/__tests__/inline-optimization.test.ts
=> [ast][compiler][mir] Eliminate hasReturn from MIR function

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/hir-tail-recursion-transformation-hir.ts
Useful for LLVM transform
`yarn test`
=> [compiler][hir] Tweak phi values for tail recursion transform

samlang-core-compiler/__tests__/mir-resource-allocator.test.ts, samlang-core-compiler/mir-resource-allocator.ts
=> [compiler] Support allocating temporaries for resource allocator

samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts
=> [ast][llvm] Fix LLVM nodes typedef

samlang-core-compiler/__tests__/llvm-types-lowering.test.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-compiler/llvm-types-lowering.ts
=> [compiler][llvm] Bootstrap LLVM lowering code

scripts/snapshot.txt, test/dev-meggo.sam
Add a very important integration test, just like [the other tests](https://github.com/SamChou19815/samlang/search?q=meggo).
`yarn test`
I am originally planning to replace 'dev' with 👩‍💻, but looks like current unicode support is not good :(
=> [test] Add an integration test

samlang-core-compiler/__tests__/llvm-constant-propagation-context.test.ts, samlang-core-compiler/llvm-constant-propagation-context.ts, samlang-core-utils/__tests__/index.test.ts, samlang-core-utils/index.ts
=> [compiler][llvm] Setup LLVMConstantPropagationContext

samlang-core-ast/__tests__/hir-types.test.ts, samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/hir-types.ts, samlang-core-ast/llvm-nodes.ts
We need this to decide whether we need a cast.
`yarn test`
=> [ast][llvm] Add isTheSameLLVMType helper function

samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts, samlang-core-compiler/llvm-lowering-translator.ts
- BITCAST -> CAST, make it auto handle all the cast cases
- PHI: allow variable number of branches to accomodate for if-else chain
`yarn test`
=> [ast][llvm] Fix nodes typedef

samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Lower HighIRStructInitializationStatement

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler] Lower let statement correctly for LLVM

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/hir-tail-recursion-transformation-hir.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][hir] Fix HIR tail recursion optimizer for LLVM

samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Correctly handle phi variables for while true

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [ast][compiler][hir] Tweak type of HIR multi-assign to help LLVM

samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Cleanup code in llvm-lowering-translator

samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Finish lowerHighIRToLLVMFunction

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [hir][compiler] Add extra move to prepare for LLVM cast

samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-constant-propagation-context.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Test LLVM function lowering

samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Finish LLVM lowering

samlang-cli/src/cli-service.ts, samlang-cli/src/index.ts, samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/index.ts, samlang-core-services/__tests__/source-processor.test.ts, samlang-core-services/index.ts, samlang-core-services/source-processor.ts, samlang-demo/src/__test__/index.test.ts, samlang-demo/src/index.ts
Currently not connected to CLI yet (although the commented code is there), because things still fail on integration tests.
`yarn test`
=> [cli][demo][service] Expose LLVM compiler

samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-compiler/mir-toplevel-lowering.ts
It's a mistake to leave it in HIR...
`yarn test`
=> [compiler][hir][mir] Move tail recursion optimization into MIR

samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Ensure that LLVM compiler rejects while true from HIR

samlang-core-analysis/__tests__/used-name-analysis.test.ts, samlang-core-analysis/used-name-analysis.ts, samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/__tests__/mir-lowering-translator.test.ts, samlang-core-compiler/hir-move-return-coalescing.ts, samlang-core-compiler/hir-tail-recursion-transformation-hir.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-compiler/mir-lowering-translator.ts, samlang-core-compiler/mir-toplevel-lowering.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
=> [ast][compiler][hir] Eliminate while true

samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts
=> [compiler][llvm] Allow having no binded value for phi branch variables

samlang-cli/src/index.ts
No guarantee on correctness yet...
`yarn test`
=> [cli] Enable LLVM ll file output

package.json, samlang-cli/package.json, samlang-demo/package.json, yarn.lock
=> [dependency] Bump ncc

samlang-core-compiler/hir-tail-recursion-transformation-hir.ts
=> [compiler][hir] Condense recursivelyPerformTailRecursiveCallTransformationOnStatements

samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] More accurate llvm match translation

samlang-core-compiler/__tests__/asm-dp-tiling.test.ts, samlang-core-compiler/__tests__/asm-toplevel-generator.test.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/__tests__/mir-basic-block-reorder.test.ts, samlang-core-compiler/__tests__/mir-basic-block.test.ts, samlang-core-compiler/__tests__/mir-lowering-translator.test.ts, samlang-core-compiler/__tests__/mir-resource-allocator.test.ts, samlang-core-compiler/asm-dp-tiling.ts, samlang-core-compiler/mir-resource-allocator.ts, samlang-core-interpreter/__tests__/mid-ir-interpreter.test.ts, samlang-core-optimization/__tests__/inline-optimization.test.ts, samlang-core-services/__tests__/source-processor.test.ts, samlang-demo/src/__test__/index.test.ts
=> [compiler] Shorten synthetic label name

samlang-core-analysis/__tests__/used-name-analysis.test.ts, samlang-core-analysis/used-name-analysis.ts, samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-flexible-op.test.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/__tests__/mir-lowering-translator.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-flexible-op.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-compiler/mir-lowering-translator.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
The goal is to make HIR closer to LLVM IR.
`yarn test`
=> [ast][compiler][hir] Turn HIR_INDEX_ACCESS into statement

samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Reduce usage of createHighIRFlexibleOrderOperatorNode

samlang-core-analysis/__tests__/used-name-analysis.test.ts, samlang-core-analysis/used-name-analysis.ts, samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-ast/llvm-nodes.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-flexible-op.test.ts, samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts, samlang-core-compiler/__tests__/hir-tail-recursion-transformation-hir.test.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/__tests__/mir-lowering-translator.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-flexible-op.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-compiler/mir-lowering-translator.ts, samlang-core-optimization/__tests__/constant-folding-optimization.test.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
=> [ast][compiler][hir] Introduce switch and turn binary from expression to statement

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
Prepare for compile time constant propagation for HIR
`yarn test`
=> [compiler][hir] Use LocalStackedContext for variable renaming

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Enable more constant propagation in HIR translation

samlang-core-analysis/__tests__/used-name-analysis.test.ts, samlang-core-analysis/used-name-analysis.ts, samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-move-return-coalescing.test.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/__tests__/mir-toplevel-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-move-return-coalescing.ts, samlang-core-compiler/hir-tail-recursion-transformation-hir.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-compiler/mir-lowering-translator.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
=> [ast][compiler][hir] Tweak conditional statements for LLVM

samlang-core-ast/__tests__/hir-types.test.ts, samlang-core-ast/hir-types.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-lowering.test.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-types-lowering.ts, samlang-core-compiler/llvm-lowering-translator.ts
Keep the LLVM translation layer minimal.
`yarn test`
=> [ast][compiler][hir] Perform cast and bind completely during HIR

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Try to reduce the number of synthetic temps

samlang-core-interpreter/llvm-ir-interpreter.ts, samlang-core-interpreter/mid-ir-interpreter.ts
=> [interpreter] Setup LLVM interpreter

samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [llvm][compiler] Use accurate label source for PHI

samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-interpreter/__tests__/llvm-ir-interpreter.test.ts, samlang-core-interpreter/llvm-ir-interpreter.ts, samlang-core-interpreter/mid-ir-interpreter.ts, samlang-core-services/__tests__/source-processor.test.ts, samlang-demo/src/__test__/index.test.ts
=> [llvm][intepreter] Unit test LLVM interpreter

samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts
=> [test][llvm] Assert LLVM compilation result pass integration testss

package.json, samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-interpreter/__tests__/llvm-ir-interpreter.test.ts, samlang-core-services/__tests__/source-processor.test.ts, samlang-demo/src/__test__/index.test.ts
Doing some local integration tests right now. Currently we are failing a lot of tests during LLVM-as.
`yarn test`
=> [ast][llvm] Fix LLVM pretty printer

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-toplevel-lowering.ts
=> [compiler][hir] Insert more potential casts due to type erasure

samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Do not jump to the end for switch for exhausive phi

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-toplevel-lowering.ts
=> [compiler][hir] Fix function related type casts

.github/workflows/integration-test.yml, samlang-cli/src/cli-service.ts, samlang-cli/src/index.ts
=> [cli] Setup assembling produced LLVM text

samlang-cli/src/cli-service.ts
=> [cli] Simplify commands

README.md
=> [readme] Update developer docs

runtime/Makefile, runtime/example.ll
=> [runtime] Simplify example

samlang-core-analysis/__tests__/control-flow-graph.test.ts, samlang-core-analysis/control-flow-graph.ts
=> [analysis] Construct CFG for LLVM instructions

samlang-core-optimization/__tests__/hir-local-value-numbering-optimization.test.ts, samlang-core-optimization/hir-local-value-numbering-optimization.ts
=> [optimization] Implement LVN optimization for HIR

samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
=> [printer][js] Insert break for switch statements

.github/workflows/integration-test.yml
=> [test][ci] Cache LLVM installation

.github/workflows/integration-test.yml, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-optimization/simple-optimizations.ts
=> [compiler][optimization][llvm] Remove unreachable LLVM code

samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts
=> [compiler][optimization] Move CCP optimization into optimization phase

samlang-core-optimization/__tests__/hir-dead-code-elimination-optimization.test.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts, samlang-core-optimization/hir-optimization-common.ts
=> [optimization] Implement DCE for HIR

samlang-core-optimization/__tests__/common-subexpression-elimination-optimization.test.ts, samlang-core-optimization/__tests__/inline-optimization.test.ts, samlang-core-optimization/inline-optimization.ts, samlang-core-optimization/optimization-resource-allocator.ts
=> [optimization] Rename synthetic variables from optimization

samlang-core-optimization/__tests__/hir-common-subexpression-elimination-optimization.test.ts, samlang-core-optimization/hir-common-subexpression-elimination-optimization.ts, samlang-core-optimization/hir-local-value-numbering-optimization.ts, samlang-core-optimization/hir-optimization-common.ts, samlang-core-utils/__tests__/index.test.ts, samlang-core-utils/index.ts
=> [optimization][hir] Implement CSE optimization on HIR

samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/inline-optimization.ts
=> [optimization] Prepare inline optimization helper functions

samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/hir-optimization-common.ts, samlang-core-optimization/inline-optimization.ts
=> [optimization] Add inline optimization on HIR

samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/index.ts
=> [test] Perform integration tests on all HIR optimizations

samlang-core-analysis/__tests__/used-name-analysis.test.ts, samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/__tests__/mir-lowering-translator.test.ts, samlang-core-compiler/__tests__/mir-toplevel-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-compiler/mir-lowering-translator.ts, samlang-core-optimization/__tests__/hir-common-subexpression-elimination-optimization.test.ts, samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts, samlang-core-optimization/__tests__/hir-dead-code-elimination-optimization.test.ts, samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/__tests__/hir-local-value-numbering-optimization.test.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/hir-local-value-numbering-optimization.ts, samlang-core-optimization/index.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
=> [ast] Tweak function call AST

samlang-core-services/__tests__/source-processor.test.ts, samlang-core-services/source-processor.ts, samlang-demo/src/__test__/index.test.ts
=> [optmization] Connect HIR optimization to prod

README.md
=> [readme] Change output from x86 to LLVM in readme

samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Optimize away unnecessary labels for if-else

samlang-core-optimization/index.ts
=> [optimization] Add a final round of local function optimization

package.json, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-optimization/index.ts, samlang-core-services/source-processor.ts, samlang-demo/src/__test__/index.test.ts
=> [compiler] Run optimizer during HIR compilation to ensure optimized JS

samlang-cli/src/cli-service.ts, samlang-cli/src/main.ts
=> [cli] Avoid compiling to HIR in-memory twice

samlang-core-analysis/control-flow-graph.ts, samlang-core-ast/llvm-nodes.ts, samlang-core-checker/__tests__/type-resolution.test.ts, samlang-core-checker/constraint-aware-checker.ts, samlang-core-checker/expression-type-checker.ts, samlang-core-checker/expression-type-fixer.ts, samlang-core-checker/statement-type-checker.ts, samlang-core-checker/type-resolution.ts, samlang-core-checker/type-undecider.ts, samlang-core-compiler/hir-types-lowering.ts, samlang-core-interpreter/llvm-ir-interpreter.ts, samlang-core-utils/__tests__/index.test.ts, samlang-core-utils/index.ts, samlang-demo/src/index.ts, scripts/compile-repository.ts, vscode/src/extension.ts
=> [repo] Add assert function

samlang-core-checker/__tests__/index.test.ts, samlang-core-checker/__tests__/module-references-collector.test.ts, samlang-core-checker/index.ts, samlang-core-checker/module-references-collector.ts
=> [checker] Collect all moduleReferences in a module

samlang-core-checker/__tests__/index.test.ts, samlang-core-checker/index.ts, samlang-core-services/language-service.ts
=> [service] Perform type based dependency analysis for LSP

samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/hir-local-value-numbering-optimization.ts, samlang-core-utils/__tests__/index.test.ts, samlang-core-utils/index.ts
=> [util] Introduce zip3 to simplify some zip code

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-optimization/__tests__/hir-common-subexpression-elimination-optimization.test.ts, samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts, samlang-core-optimization/__tests__/hir-dead-code-elimination-optimization.test.ts, samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/__tests__/hir-local-value-numbering-optimization.test.ts, samlang-core-optimization/__tests__/hir-unused-name-elimination-optimization.test.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/hir-local-value-numbering-optimization.ts, samlang-core-optimization/hir-optimization-common.ts, samlang-core-optimization/hir-unused-name-elimination-optimization.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
Another preparation for while and break statements.
`yarn test`
=> [ast] Turn switch final assignments into a list

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts, samlang-core-optimization/__tests__/hir-dead-code-elimination-optimization.test.ts, samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/__tests__/hir-local-value-numbering-optimization.test.ts, samlang-core-optimization/__tests__/hir-unused-name-elimination-optimization.test.ts, samlang-core-optimization/hir-common-subexpression-elimination-optimization.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/hir-local-value-numbering-optimization.ts, samlang-core-optimization/hir-unused-name-elimination-optimization.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
Right now we are not emitting any whiles. Tailrec optimization and LLVM support will be introduced in later diffs.
`yarn test`
=> [ast][hir][optimization] Reintroduce while statement and support it in existing optimizations

samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
=> [printer][js] Adjust JS printer to fix do while condition var scope issue

samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-optimization/__tests__/hir-tail-recursion-optimization.test.ts, samlang-core-optimization/hir-tail-recursion-optimization.ts, samlang-core-optimization/index.ts, samlang-core-optimization/optimization-resource-allocator.ts, samlang-core-utils/index.ts
=> [optimization][hir] Perform tailrec optimization

samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-optimization/__tests__/hir-tail-recursion-optimization.test.ts, samlang-core-optimization/hir-tail-recursion-optimization.ts
Make the flow more linear to help optimizations.
`yarn test`
=> [optimization] Move out if-else code without break

samlang-core-ast/hir-expressions.ts, samlang-core-ast/hir-flexible-op.ts, samlang-core-optimization/__tests__/hir-common-subexpression-elimination-optimization.test.ts
=> [ast][hir] Also transform minus constant in createHighIRFlexibleOrderOperatorNode

samlang-cli/src/cli-service.ts
=> [cli] Cleanup not human-readable intermediate files after compile

samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
=> [printer][js] Do not break label in JS after switch is gone

samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Rename a translator function

package.json, samlang-cli/build.js, samlang-cli/package.json, yarn.lock
It's so much faster!
`yarn test`
=> [cli] Adopt esbuild to bundle cli

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-optimization/__tests__/hir-common-subexpression-elimination-optimization.test.ts, samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts, samlang-core-optimization/__tests__/hir-dead-code-elimination-optimization.test.ts, samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/__tests__/hir-local-value-numbering-optimization.test.ts, samlang-core-optimization/__tests__/hir-tail-recursion-optimization.test.ts, samlang-core-optimization/__tests__/hir-unused-name-elimination-optimization.test.ts, samlang-core-optimization/hir-common-subexpression-elimination-optimization.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/hir-local-value-numbering-optimization.ts, samlang-core-optimization/hir-optimization-common.ts, samlang-core-optimization/hir-tail-recursion-optimization.ts, samlang-core-optimization/hir-unused-name-elimination-optimization.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
Break down the weird and complex if-else into simpler components, which helps to reduce a lot of ugly null checks.
`yarn test`
=> [ast][hir] Introduce single if and break statement

.gitattributes
=> [runtime] Mark gc code as generated

samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts
=> [optimization] Remove unreachable statements after break

samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts
=> [optimization] Optimize loops that only run once

samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts, samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-printer/__tests__/printer-js.test.ts
=> [optimization] Constant folding first few iterations of loop

samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts
=> [optimization] Let plus expressions propagate to comparison

samlang-core-ast/hir-expressions.ts, samlang-core-optimization/__tests__/hir-loop-analysis.test.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts, samlang-core-optimization/hir-loop-analysis.ts
=> [optimization] Create loop analysis

samlang-core-optimization/__tests__/hir-loop-invariant-code-motion.test.ts, samlang-core-optimization/hir-loop-invariant-code-motion.ts
=> [optimization] Implement conservative loop invariant code motion

samlang-core-optimization/__tests__/hir-loop-induction-analysis.test.ts, samlang-core-optimization/hir-loop-induction-analysis.ts
=> [optimization] Make loop induction analysis support loop invariants

samlang-core-optimization/__tests__/hir-loop-induction-analysis.test.ts, samlang-core-optimization/hir-loop-induction-analysis.ts
=> [optimization] Improve loop induction analysis

samlang-core-optimization/__tests__/hir-loop-optimizations.test.ts, samlang-core-optimization/hir-loop-induction-analysis.ts, samlang-core-optimization/hir-loop-optimizations.ts, samlang-core-optimization/optimization-resource-allocator.ts
=> [optimization] Setup highIRLoopAlgebraicOptimization

samlang-core-optimization/__tests__/hir-loop-algebraic-optimization.test.ts, samlang-core-optimization/hir-loop-algebraic-optimization.ts
=> [optimization] Rename files

samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-optimization/index.ts
=> [optimization] Ensure all optimizations are tested in isolation

samlang-core-optimization/__tests__/hir-loop-algebraic-optimization.test.ts, samlang-core-optimization/__tests__/hir-loop-induction-analysis.test.ts, samlang-core-optimization/__tests__/hir-loop-induction-variable-elimination.test.ts, samlang-core-optimization/hir-loop-induction-analysis.ts, samlang-core-optimization/hir-loop-induction-variable-elimination.ts
=> [optimization] Implement loop induction variable elimination

samlang-core-optimization/__tests__/hir-loop-strength-reduction.test.ts, samlang-core-optimization/hir-loop-strength-reduction.ts
=> [optimization] Implement strength reduction

samlang-core-optimization/__tests__/hir-loop-optimizations.test.ts, samlang-core-optimization/hir-loop-optimizations.ts
=> [optimization] Implement connector for all loop optimizations

samlang-core-optimization/__tests__/hir-loop-induction-analysis.test.ts, samlang-core-optimization/__tests__/hir-loop-optimizations.test.ts, samlang-core-optimization/hir-loop-induction-analysis.ts, samlang-core-optimization/hir-loop-optimizations.ts
=> [optimization] Fix guard operator inversion

package.json, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-optimization/__tests__/hir-loop-optimizations.test.ts, samlang-core-optimization/hir-loop-optimizations.ts, samlang-core-optimization/index.ts, scripts/compile-repository.ts
=> [optimization][test] Make loop optimization part of integration test

samlang-core-optimization/__tests__/hir-loop-optimizations.test.ts
=> [optimization][loop] Add one more loop test from compiler notes

samlang-core-integration-tests/test-programs.ts, samlang-core-optimization/__tests__/hir-loop-optimizations.test.ts, samlang-core-optimization/hir-loop-induction-variable-elimination.ts, samlang-core-optimization/hir-loop-optimizations.ts, samlang-core-optimization/hir-optimization-common.ts, scripts/snapshot.txt, test/loop-optimization.sam
Without the filtering, name collision will occur.
`yarn test`
=> [optimization] Filter away statements that are covered by new loop variables

README.md
LICM is already productionized!
`yarn test`
=> [readme] Update Planned Optimizations

samlang-core-optimization/__tests__/hir-loop-optimizations.test.ts, samlang-core-optimization/hir-loop-induction-analysis.ts
=> [optimization] Make induction variable analysis more flexible

.github/workflows/full-integration-test.yml, samlang-cli/src/cli-service.ts, scripts/compile-repository.ts
=> [cli] Allow LLVM emit to be skipped if no LLVM toolchain is detected

samlang-cli/package.json, samlang-demo/build.js, samlang-demo/package.json, samlang-demo/src/index.ts, samlang-dummy/package.json, yarn.lock
=> [repo] Publish 0.4.0

samlang-cli/package.json, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts, samlang-demo/package.json, samlang-dummy/package.json, yarn.lock
Now that we eliminated the break embedded into if-else, we no longer needs the while hack.
`yarn test`
=> [printer][js] Avoid using var

samlang-core-optimization/__tests__/hir-dead-code-elimination-optimization.test.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts
=> [optimization] Perform more DCE on loops

samlang-core-optimization/hir-dead-code-elimination-optimization.ts
=> [optimization] Tweak DCE optimization code

samlang-core-optimization/hir-loop-optimizations.ts
=> [optimization] Filter statements before expanding optimizable loop

samlang-core-optimization/__tests__/hir-loop-optimizations.test.ts, samlang-core-optimization/hir-loop-optimizations.ts
=> [optimization] Eliminate unused loop variables

samlang-cli/package.json, samlang-demo/package.json
=> [repo] Publish 0.4.2

samlang-core-parser/index.ts
=> [parser] Replace deprecated ANTLRInputStream with CharStreams

samlang-core-parser/__tests__/parser-comment-collector.test.ts, samlang-core-parser/parser-class-builder.ts, samlang-core-parser/parser-comment-collector.ts
=> [parser] Collect all comments

samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
=> [service] Do not format documents with syntax errors

samlang-cli/src/lsp.ts, samlang-core-ast/samlang-toplevel.ts, samlang-core-checker/__tests__/global-typing-context-builder.test.ts, samlang-core-checker/__tests__/index.test.ts, samlang-core-checker/__tests__/undefined-import-checker.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-parser/__tests__/parser-comment-collector.test.ts, samlang-core-parser/index.ts, samlang-core-parser/parser-class-builder.ts, samlang-core-parser/parser-comment-collector.ts, samlang-core-parser/parser-module-builder.ts, samlang-core-services/location-service.ts
=> [parser] Put class doc into class definition AST

samlang-cli/src/lsp.ts, samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
=> [service][lsp] Show documents for hover for class

samlang-core-printer/__tests__/printer-prettier-core.test.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-printer/printer-prettier-core.ts, samlang-core-printer/printer-source-level.ts, test/print-hello-world.sam
=> [printer] Print out document string for class

samlang-core-ast/samlang-toplevel.ts, samlang-core-checker/__tests__/global-typing-context-builder.test.ts, samlang-core-checker/__tests__/index.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-parser/parser-class-builder.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-printer/printer-source-level.ts, test/print-hello-world.sam
=> [ast][parser][printer] Collect and pretty print functions level doc strings

package.json, samlang-cli/src/configuration/__tests__/configuration-loader.test.ts, samlang-cli/src/configuration/configuration-loader.ts, samlang-core-ast/common-nodes.ts, samlang-core-ast/hir-flexible-op.ts, samlang-core-checker/__tests__/type-validator.test.ts, samlang-core-checker/module-references-collector.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-types-lowering.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-compiler/llvm-types-lowering.ts, samlang-core-interpreter/source-level-interpreter.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-printer/printer-source-level.ts, scripts/compile-repository.ts, vscode/src/extension.ts, yarn.lock
=> [eslint] Update linter to work better with TS

samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
=> [lsp] Make language service give doc string for functions/methods

.yarn/sdks/typescript/package.json, samlang-cli/src/configuration/configuration-parser.ts, samlang-core-checker/expression-type-checker.ts, samlang-core-parser/parser-class-builder.ts
=> [misc] Simple code cleanup

samlang-core-parser/samlang-lexer.ts
=> [parser] Setup incomplete lexer stub

samlang-core-parser/__tests__/samlang-lexer.test.ts, samlang-core-parser/samlang-lexer.ts
=> [parser] Enforce string escape check

samlang-core-parser/samlang-lexer.ts, samlang-core-parser/samlang-parser.ts
=> [parser] samlang-parser setup

samlang-core-parser/samlang-lexer.ts, samlang-core-parser/samlang-parser.ts
=> [parser] Setup samlang type parser

scripts/compile-repository.ts
=> [script] Remove useless ts-check

samlang-core-parser/samlang-parser.ts
=> [parser] Parse some base expressions

samlang-core-parser/samlang-lexer.ts, samlang-core-parser/samlang-parser.ts
=> [parser] Finish nested expression and lambda parsing

samlang-core-parser/samlang-parser.ts
=> [parser] Parse object literal

samlang-core-parser/samlang-parser.ts
=> [parse] Parse unary, function call and field access

samlang-core-parser/samlang-parser.ts
=> [parser] Parse all binary expressions and if-else

samlang-core-parser/samlang-parser.ts
=> [parser] Parse match expressions

samlang-core-parser/samlang-parser.ts
=> [parser] Parse all expressions

samlang-core-parser/parser-comment-collector.ts, samlang-core-parser/samlang-parser.ts
=> [parser] Parse class member definition

samlang-core-ast/samlang-toplevel.ts, samlang-core-parser/samlang-lexer.ts, samlang-core-parser/samlang-parser.ts
=> [parser] Support parsing the entire module

samlang-core-parser/__tests__/index.test.ts, samlang-core-parser/samlang-parser.ts
=> [parser] Fix some parser bugs

samlang-core-parser/__tests__/index.test.ts, samlang-core-parser/__tests__/samlang-lexer.test.ts, samlang-core-parser/samlang-parser.ts, samlang-core-services/__tests__/source-processor.test.ts
=> [parser] Fix more parser issues

samlang-core-parser/__tests__/samlang-lexer.test.ts, samlang-core-parser/samlang-lexer.ts, samlang-core-parser/samlang-parser.ts
All tests except integration tests are passing!
`yarn test`
=> [parser] Fix most of the parser errors

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/hir-expressions.ts, samlang-core-checker/expression-type-fixer.ts, samlang-core-checker/module-type-checker.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-interpreter/__tests__/llvm-ir-interpreter.test.ts, samlang-core-interpreter/llvm-ir-interpreter.ts, samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/__tests__/hir-loop-induction-analysis.test.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/hir-loop-induction-analysis.ts, samlang-core-optimization/hir-optimization-common.ts, samlang-core-parser/__tests__/index.test.ts, samlang-core-parser/__tests__/samlang-parser.test.ts, samlang-core-parser/samlang-lexer.ts, samlang-core-parser/samlang-parser.ts, samlang-core-printer/printer-prettier-core.ts, samlang-core-printer/printer-source-level.ts, samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
=> [test] Add more tests

samlang-core-optimization/__tests__/hir-dead-code-elimination-optimization.test.ts, samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/__tests__/hir-loop-induction-analysis.test.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/hir-loop-induction-analysis.ts, samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
No more coverage suppression.
`yarn test`
=> [tests] Actual 100% test coverage

babel.config.js, package.json, yarn.lock
=> [repo] Use esbuild runner for test code transpilation

samlang-core-integration-tests/__tests__/checker-integration-test.test.ts, samlang-core-parser/samlang-parser.ts
=> [parser] Adjust error message wording

samlang-core-parser/samlang-parser.ts
=> [parser] Implement collectPrecedingComments for later comment parsing

samlang-core-ast/common-nodes.ts, samlang-core-parser/samlang-parser.ts
=> [ast][parser] Promote TypedComment to AST Node

samlang-cli/package.json, samlang-demo/package.json, yarn.lock
=> [repo] Bump esbuild

samlang-core-ast/samlang-expressions.ts, samlang-core-checker/__tests__/expression-type-checker.test.ts, samlang-core-checker/__tests__/expression-type-fixer.test.ts, samlang-core-checker/__tests__/global-typing-context-builder.test.ts, samlang-core-checker/__tests__/index.test.ts, samlang-core-checker/__tests__/module-references-collector.test.ts, samlang-core-checker/__tests__/statement-type-checker.test.ts, samlang-core-checker/expression-type-checker.ts, samlang-core-checker/statement-type-checker.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-interpreter/__tests__/source-level-interpreter.test.ts, samlang-core-interpreter/source-level-interpreter.ts, samlang-core-parser/samlang-parser.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-services/location-service.ts
=> [ast] Add preceding comments to all expressions

samlang-cli/package.json, samlang-cli/src/lsp.ts, yarn.lock
=> [cli] Bump language server

samlang-core-printer/__tests__/printer-prettier-core.test.ts, samlang-core-printer/printer-prettier-core.ts
=> [printer][prettier] Support hardline in prettier core

samlang-core-printer/__tests__/printer-prettier-core.test.ts, samlang-core-printer/printer-prettier-core.ts, samlang-core-printer/printer-source-level.ts
Make the caller add it.
`yarn test`
=> [printer][core] Do not include line ending for comments

samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-printer/printer-prettier-core.ts, samlang-core-printer/printer-source-level.ts, test/cf-test-1.sam, test/correct-op.sam
=> [printer][source] Pretty-print parsed preceding comments

samlang-core-parser/samlang-parser.ts, samlang-core-printer/printer-source-level.ts, test/cf-test-1.sam
=> [printer][source] Print inner comments for parsed ones

samlang-core-ast/samlang-expressions.ts, samlang-core-checker/__tests__/expression-type-checker.test.ts, samlang-core-checker/__tests__/expression-type-fixer.test.ts, samlang-core-checker/__tests__/module-references-collector.test.ts, samlang-core-checker/__tests__/statement-type-checker.test.ts, samlang-core-checker/expression-type-checker.ts, samlang-core-checker/statement-type-checker.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-interpreter/__tests__/source-level-interpreter.test.ts, samlang-core-interpreter/source-level-interpreter.ts, samlang-core-parser/samlang-parser.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-printer/printer-source-level.ts, samlang-core-services/location-service.ts
=> [ast] precedingComments -> associatedComments

samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-printer/printer-source-level.ts, test/cf-test-1.sam
=> [printer][source] Fix source-level comment printing logic

samlang-core-parser/samlang-parser.ts
=> [parser] Parse all following comments in comma separated expressions

package.json, samlang-cli/src/lsp.ts, samlang-core-checker/__tests__/index.test.ts, samlang-core-checker/expression-type-checker.ts, samlang-core-checker/index.ts, samlang-core-checker/type-validator.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-interpreter/source-level-interpreter.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-parser/samlang-lexer.ts, samlang-core-parser/samlang-parser.ts, samlang-core-printer/printer-prettier-core.ts, yarn.lock
=> [eslint] Adopt new eslint config

samlang-core-ast/samlang-toplevel.ts, samlang-core-checker/__tests__/global-typing-context-builder.test.ts, samlang-core-checker/__tests__/index.test.ts, samlang-core-checker/__tests__/undefined-import-checker.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-parser/samlang-parser.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-printer/printer-source-level.ts, samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
=> [ast] Unify associated comment type

samlang-core-ast/samlang-expressions.ts, samlang-core-checker/__tests__/expression-type-fixer.test.ts, samlang-core-checker/__tests__/module-references-collector.test.ts, samlang-core-checker/expression-type-checker.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-interpreter/__tests__/source-level-interpreter.test.ts, samlang-core-parser/samlang-parser.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-printer/printer-source-level.ts, test/block-in-if-else.sam, test/create-variants.sam, test/cse-test-5.sam, test/generic-object-test.sam, test/if-else-same-variable-name.sam
=> [parser] Parse more comments

samlang-runtime/gc.c, samlang-runtime/gc.h, samlang-runtime/libsam.c
=> [runtime] Reformat

samlang-runtime/gc.c, samlang-runtime/gc.h, samlang-runtime/libsam.c, samlang-runtime/libsam.h
=> [runtime] Drop windows support

package.json, samlang-dev, samlang-runtime/gc.c, scripts/compile-repository.ts
=> [runtime] Make runtime code platform independent

samlang-cli/build.js, samlang-demo/build.js
=> [repo] Target es2017 when bundling

samlang-cli/build.js, samlang-cli/package.json, samlang-demo/build.js, samlang-demo/package.json, yarn.lock
=> [dependency] Use officially maintained @yarnpkg/esbuild-plugin-pnp

package.json, samlang-cli/package.json, samlang-demo/package.json, yarn.lock
=> [esbuild] Pin esbuild to a single version

.github/workflows/full-integration-test.yml
=> [ci] Adopt LLVM12

samlang-cli/package.json, samlang-demo/package.json
=> [repo] Publish new version of samlang with comment parsing

jest-esbuild-transformer/index.js, jest-esbuild-transformer/package.json, jest-esbuild-transformer/tsconfig.json, package.json, samlang-cli/package.json, samlang-demo/package.json, scripts/compile-repository.js, yarn.lock
=> [repo] Publish @dev-sam/jest-esbuild-transformer

.github/workflows/full-integration-test.yml, scripts/compile-repository.js, scripts/snapshot.txt, test/benchmark.sam
=> [test] Add a benchmark test

test/benchmark.sam
=> [test] Make benchmark test run faster

.vscode/settings.json, samlang-runtime/gc.c
=> [runtime] Slight gc library tweak

samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts, samlang-demo/src/__test__/index.test.ts, scripts/snapshot.txt, test/gc.sam
=> [printer][js] Fix bigint printing

.github/workflows/full-integration-test.yml, samlang-runtime/gc.c, samlang-runtime/gc.h, test/gc.sam
=> [runtime] Eliminate one assembly instruction

samlang-runtime/gc.c, samlang-runtime/gc.h
=> [runtime] Adjust GC memory size

package.json
=> [repo] Auto format js files as well

samlang-cli/build.js, samlang-demo/build.js
=> [repo] Produce sourcemaps along with bundles

samlang-core-parser/__tests__/index.test.ts, samlang-core-parser/samlang-parser.ts, test/and-or-inside-if.sam
=> [parser] Fix parser unconsume function to skip over comments

samlang-cli/package.json, samlang-demo/package.json
=> [repo] Release 0.4.4

samlang-cli/src/lsp.ts
=> [lsp] Minor refactors

samlang-cli/src/lsp.ts, samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
=> [lsp] Bootstrap code for renaming service

samlang-core-services/__tests__/variable-definition-service.test.ts, samlang-core-services/variable-definition-service.ts
=> [service] Implement service that allows accurate location lookup

samlang-core-services/language-service.ts
=> [services] Factor out updateLocationLookupsForCheckedModules

samlang-core-services/__tests__/variable-definition-service.test.ts, samlang-core-services/variable-definition-service.ts
The range shouldn't be conflicting each other. So it should be safe.
`yarn test`
=> [service] Make `VariableDefinitionLookup` support entire module

samlang-core-services/__tests__/variable-definition-service.test.ts, samlang-core-services/variable-definition-service.ts
=> [service] Create VariableDefinitionLookup that works with all sources

samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts, samlang-core-services/variable-definition-service.ts
=> [service] Implement variable definition lookup using better infra

.github/workflows/bump.yml
=> [ci] Fix bump bot

package.json
=> [repo] Remove unused husky hook

samlang-core-services/__tests__/language-service.test.ts
=> [service] Reorder tests

samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts, samlang-core-services/variable-definition-service.ts
=> [service] Added tests to ensure failed rename works without crash

samlang-core-services/__tests__/variable-definition-service.test.ts, samlang-core-services/package.json, samlang-core-services/variable-definition-service.ts, yarn.lock
=> [service] Implement apply renaming

samlang-cli/src/lsp.ts, samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
=> [service][lsp][cli] Connect rename service to LSP

samlang-cli/src/lsp.ts
=> [lsp] Unbreak goto definition command uri returns

samlang-core-ast/__tests__/common-names.test.ts, samlang-core-ast/__tests__/common-nodes.test.ts, samlang-core-ast/common-nodes.ts, samlang-core-checker/__tests__/constraint-aware-checker.test.ts, samlang-core-checker/__tests__/expression-type-fixer.test.ts, samlang-core-checker/__tests__/module-references-collector.test.ts, samlang-core-checker/__tests__/statement-type-checker.test.ts, samlang-core-checker/__tests__/type-identifier-replacer.test.ts, samlang-core-checker/__tests__/type-resolver.test.ts, samlang-core-checker/__tests__/type-undecider.test.ts, samlang-core-checker/__tests__/type-validator.test.ts, samlang-core-checker/__tests__/typing-context.test.ts, samlang-core-checker/__tests__/undecided-type-collector.test.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-lowering.test.ts, samlang-core-interpreter/__tests__/source-level-interpreter.test.ts, samlang-core-parser/__tests__/index.test.ts, samlang-core-parser/__tests__/samlang-parser.test.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-services/__tests__/variable-definition-service.test.ts
Use ModuleReference.DUMMY for testing instead...
`yarn test`
=> [repo][ast] Reserve ModuleReference.ROOT for special purpose

samlang-cli/package.json, samlang-cli/src/lsp.ts, samlang-cli/src/main.ts, samlang-core-checker/__tests__/expression-type-checker.test.ts, samlang-core-checker/__tests__/global-typing-context-builder.test.ts, samlang-core-checker/__tests__/index.test.ts, samlang-core-checker/global-typing-context-builder.ts, samlang-core-checker/index.ts, samlang-core-integration-tests/__tests__/checker-integration-test.test.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-integration-tests/__tests__/printer-integration-test.test.ts, samlang-core-integration-tests/package.json, samlang-core-interpreter/__tests__/source-level-interpreter.test.ts, samlang-core-interpreter/package.json, samlang-core-parser/__tests__/index.test.ts, samlang-core-parser/__tests__/samlang-parser.test.ts, samlang-core-parser/index.ts, samlang-core-parser/samlang-parser.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/__tests__/location-service.test.ts, samlang-core-services/__tests__/source-processor.test.ts, samlang-core-services/__tests__/variable-definition-service.test.ts, samlang-core-services/language-service.ts, samlang-core-services/source-processor.ts, samlang-demo/package.json, samlang-demo/src/index.ts, yarn.lock
=> [parser][checker] Setup `builtinModuleTypes`

samlang-cli/src/main.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-printer/printer-source-level.ts, scripts/snapshot.txt, test/short-circuit-and-or.sam
=> [printer] Reduce number of exponential behaviors

samlang-core-services/__tests__/language-service.test.ts, samlang-core-services/language-service.ts
Now we have injectable standard libraries. This can actually happen.
`yarn test`
=> [service] Do not make LSP crash when cannot find definition

.yarnrc.yml, package.json, samlang-core-utils/__tests__/index.test.ts, yarn.lock
=> [repo] Adopt jest 27

samlang-core-compiler/__tests__/hir-type-synthesizer.test.ts, samlang-core-compiler/hir-type-synthesizer.ts
=> [compiler][hir] Setup HighIRTypeSynthesizer

samlang-core-ast/__tests__/hir-expressions.test.ts, samlang-core-ast/__tests__/hir-types.test.ts, samlang-core-ast/hir-toplevel.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-synthesizer.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-compiler/hir-type-synthesizer.ts, samlang-core-compiler/hir-types-lowering.ts, samlang-core-printer/__tests__/printer-js.test.ts
=> [compiler][hir] Generate id types from struct types

samlang-core-ast/__tests__/hir-types.test.ts, samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/hir-types.ts, samlang-core-ast/llvm-nodes.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-lowering.test.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/__tests__/llvm-types-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-types-lowering.ts, samlang-core-compiler/llvm-types-lowering.ts, samlang-core-interpreter/__tests__/llvm-ir-interpreter.test.ts
=> [compiler][hir][llvm] Eliminate all struct types

samlang-core-optimization/hir-unused-name-elimination-optimization.ts
=> [optimization] Collect used types from function parameters

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts
=> [compiler][hir][test] Assert content of synthetic types as well

samlang-core-compiler/__tests__/mir-expression-lowering.test.ts, samlang-core-compiler/mir-expression-lowering.ts, samlang-core-compiler/mir-toplevel-lowering.ts, test/various-syntax-forms.sam
=> [compiler][mir] Uniform closure call without branching

.yarnrc.yml, package.json, yarn.lock
=> [repo] Adopt latest jest to remove packageExtensions

samlang-core-ast/__tests__/hir-nodes.test.ts, samlang-core-ast/hir-nodes.ts
=> [ast][hir] Setup basic HIR types

package.json, yarn.lock
=> [repo] Adopt latest jest that contains my dependency fixes

package.json, samlang-core-ast/__tests__/hir-nodes.test.ts, samlang-core-ast/hir-nodes.ts
=> [ast][hir] Setup HighIRTypeDefinition

samlang-core-compiler/__tests__/hir-string-manager.test.ts, samlang-core-compiler/__tests__/mir-expression-lowering.test.ts, samlang-core-compiler/hir-string-manager.ts, samlang-core-compiler/mir-expression-lowering.ts, samlang-core-compiler/mir-toplevel-lowering.ts
=> [compiler][hir] Rename `MidIRStringManager` to `HighIRStringManager`

samlang-core-ast/__tests__/hir-nodes.test.ts, samlang-core-ast/hir-nodes.ts
=> [ast][hir] Make HIR functions include generic type parameters

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [ast][hir] Setup type conversion functions

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Avoid generating unused generic types

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
See the TODO comment for its limitations. More principled solutions will be introduced later. This just serves as a starting point of reasoning.
`yarn test`
=> [compiler][hir] Implement a naive toplevel function type conversion

samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Add addition note on how to translate types

samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Setup basic structure for HIR expression lowering

samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Finish porting HIR expression lowering translator

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Fix and test expression lowering

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Give a different context parameter for each function type

samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Reduce number of `this.lowerType(...)` calls

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
This is needed to unblock further HIR compiler work.
`yarn test`
=> [compiler][hir] Implement `highIRTypeApplication` helper function

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Correctly resolve type mapping for HIR types

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Make the variable context fully populated for all tests

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Use variable resolutions for lambda translation

samlang-core-parser/samlang-lexer.ts
=> [parser] Ban `constructor` and `destructor` as keywords

samlang-core-checker/expression-type-fixer.ts, samlang-core-integration-tests/test-programs.ts, test/various-syntax-forms.sam
=> [checker] Resolve an previously unresolved data variable type

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Introduce a mode for type lowerer to avoid turning functions into closures

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Fix behavior of translating function type for non-toplevel context

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Correctly lower toplevel types with generics

samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Factor out special type refactors into their own functions

samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Preserve existing source-level generic types

samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Document `SamlangTypeLoweringManager` challenges

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Fix problem where the compiler generates unbounded type parameters

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Use `lowerSamlangFunctionTypeForTopLevel` infra

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Fork `lowerSamlangType` into specialized `lowerSamlangTypeForLocalValues`

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Specialize `lowerSamlangType` into `lowerSamlangTypeForTypeDefinition`

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Unify some over-specialized code

samlang-core-compiler/hir-type-conversion.ts
Sadly, the current approach will cause infinite types in the case of recursive types. This diff adds it here to document the failed process.
`yarn test`
=> [compiler][hir] Check in unsuccessful `solveIdentifierTypeUnderConstraint`

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Remove deprecated type lowering

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Refactor expression lowering

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Refactor `SamlangTypeLoweringManager.lowerSamlangTypeDefinition`

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Avoid special case `this` translation

samlang-core-ast/__tests__/hir-nodes.test.ts, samlang-core-ast/hir-nodes.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts
=> [hir] Rename `HighIRModule` to `HighIRSources`

samlang-core-ast/__tests__/hir-nodes.test.ts, samlang-core-ast/hir-nodes.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Lower all sources into HIR sources

samlang-core-ast/__tests__/hir-nodes.test.ts, samlang-core-ast/hir-nodes.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Correctly deal with closure context type

samlang-core-compiler/hir-toplevel-lowering.ts
=> [compiler][hir] Refactor toplevel lowering to make it more readable

samlang-core-ast/hir-nodes.ts
=> [ast][hir] Restrict possible types of HIR_NAME

samlang-core-compiler/hir-generics-specialization.ts, samlang-core-compiler/hir-toplevel-lowering.ts
=> [compiler][hir] Implement `GenericsUsageCollector`

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Add helper method to solve type arguments

samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-toplevel-lowering.ts
=> [compiler][hir] Remove needs for `functionTypeMapping`

samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Rename an encoder function to reduce confusion

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Add function to encode HIR identifier type

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Create more general `encodeHighIRIdentifierTypeAfterGenericsSpecialization`

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Fix order of HIR type parameter solution

samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-generics-specialization.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Implement generics specialization

samlang-core-compiler/__tests__/hir-generics-specialization.test.ts
=> [compiler][hir] Tests for generics specialization

samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/hir-toplevel-lowering.ts
=> [compiler][hir] Connect generics specialization code to prod

samlang-core-compiler/__tests__/hir-generics-specialization.test.ts, samlang-core-compiler/hir-generics-specialization.ts
Close #548.
Close #549.
Close #550.
Close #551.
`yarn test`
=> [compiler][hir] Make generics specialization correctly handle no-arg rewrites

samlang-core-compiler/__tests__/hir-generics-specialization.test.ts, samlang-core-compiler/hir-generics-specialization.ts
=> [compiler][hir] Purge unused names during generics specialization

samlang-core-ast/__tests__/hir-nodes.test.ts, samlang-core-ast/hir-nodes.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-generics-specialization.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-generics-specialization.ts, samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-compiler/hir-type-conversion.ts
=> [hir] Synthesize closure type definitions

samlang-core-ast/hir-nodes.ts, samlang-core-compiler/hir-generics-specialization.ts
=> [ast][hir] Restrict type for `HIR_FUNCTION_CALL`

samlang-core-ast/hir-nodes.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Redefine meaning of `HighIRFunctionCallStatement`

samlang-core-ast/mir-nodes.ts, samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/mir-sources-lowering.ts
=> [compiler][mir] Compile HIR sources to MIR sources

samlang-cli/src/cli-service.ts, samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/mir-sources-lowering.ts, samlang-core-compiler/mir-toplevel-lowering.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-optimization/__tests__/mir-unused-name-elimination-optimization.test.ts, samlang-core-optimization/index.ts, samlang-core-optimization/mir-unused-name-elimination-optimization.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/index.ts, samlang-core-printer/printer-js.ts, samlang-demo/src/index.ts
=> [optimization][mir] Make MIR optimizations work on sources

samlang-core-compiler/index.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-interpreter/__tests__/llvm-ir-interpreter.test.ts, samlang-core-interpreter/llvm-ir-interpreter.ts
=> [interpreter][llvm] Allow customization of main function

samlang-core-compiler/__tests__/mir-toplevel-lowering.test.ts, samlang-core-compiler/mir-toplevel-lowering.ts, samlang-core-optimization/index.ts, samlang-core-services/__tests__/source-processor.test.ts, samlang-demo/src/__test__/index.test.ts
=> [compiler][mir] Prepare for generating single `MidSources`

samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/printer-js.ts
=> [printer][js] Support pretty printing for single `MidIRSources`

samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Better debugging for missing variable resolution

samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Ensure all variables are resolved in lambda

samlang-core-compiler/__tests__/hir-generics-specialization.test.ts, samlang-core-compiler/hir-generics-specialization.ts
=> [compiler][hir] Make generics specialization tolerate builtins

samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/mir-expression-lowering.ts, samlang-core-compiler/mir-sources-lowering.ts, samlang-core-interpreter/llvm-ir-interpreter.ts, samlang-core-optimization/control-flow-graph.ts, samlang-core-utils/__tests__/index.test.ts, samlang-core-utils/index.ts
=> [utils] Support custom message of `checkNotNull`

samlang-core-compiler/hir-expression-lowering.ts, samlang-core-compiler/hir-generics-specialization.ts, samlang-core-compiler/hir-type-conversion.ts, samlang-core-compiler/mir-toplevel-lowering.ts, samlang-core-compiler/mir-type-synthesizer.ts, samlang-core-optimization/control-flow-graph.ts, samlang-core-optimization/mir-inline-optimization.ts, samlang-core-optimization/mir-loop-strength-reduction.ts, samlang-core-services/language-service.ts
=> [repo] Add more debug information for `checkNotNull` calls

samlang-core-compiler/__tests__/hir-generics-specialization.test.ts, samlang-core-compiler/__tests__/hir-type-conversion.test.ts, samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Resolve generics specialization already-specialized problem

samlang-core-compiler/hir-type-conversion.ts
=> [compiler][hir] Add missing type application

samlang-core-printer/printer-prettier-core.ts
=> [printer][core] Optimize prettier core algorithm to reduce deep recursions

samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-printer/index.ts, samlang-core-printer/printer-js.ts, samlang-demo/src/__test__/index.test.ts, samlang-demo/src/index.ts
=> [printer][js] Connect `createPrettierDocumentForExportingModuleFromMidIRSources` to prod

.github/workflows/full-integration-test.yml, .github/workflows/integration-test.yml
=> [ci] Simplify CI config by using auto yarn cache

samlang-core-services/__tests__/source-processor.test.ts, samlang-core-services/index.ts, samlang-core-services/source-processor.ts, samlang-demo/src/index.ts
=> [services] Inline `lowerSourcesToLLVMModules` into demo code

samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts
=> [compiler][llvm] Add alternative LLVM toplevel compiler function

samlang-core-compiler/__tests__/hir-type-deduplication.test.ts, samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-compiler/hir-type-deduplication.ts, scripts/compile-repository.ts
=> [compiler][hir] Deduplicate HIR types

samlang-cli/src/cli-service.ts, samlang-core-ast/__tests__/llvm-nodes.test.ts, samlang-core-ast/llvm-nodes.ts, samlang-core-compiler/__tests__/llvm-lowering-translator.test.ts, samlang-core-compiler/llvm-lowering-translator.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-interpreter/__tests__/llvm-ir-interpreter.test.ts, samlang-core-interpreter/llvm-ir-interpreter.ts, samlang-demo/src/__test__/index.test.ts, samlang-demo/src/index.ts
=> [repo] Replace collection of LLVM modules with LLVMSources

samlang-core-ast/samlang-expressions.ts, samlang-core-parser/samlang-parser.ts
=> [parser] Fix precedence level of source level expressions

Tests/AllTests.sam, Tests/StdLib.sam, scripts/compile-repository.ts, scripts/snapshot.txt
=> [tests] Simplify test script

samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/index.ts, samlang-core-printer/printer-js.ts
=> [printer] Simplify JS printers

samlang-core-ast/__tests__/mir-nodes.test.ts, samlang-core-ast/mir-nodes.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-printer/__tests__/printer-js.test.ts, samlang-core-printer/index.ts, samlang-core-printer/printer-js.ts, samlang-demo/src/__test__/index.test.ts
=> [printer] Simplify more JS printing

samlang-cli/src/main.ts, samlang-core-printer/printer-prettier-core.ts
=> [printer][core] Improve performance by memoization

samlang-core-ast/__tests__/mir-nodes.test.ts, samlang-core-ast/mir-nodes.ts
=> [ast] Support pretty-print to JS in MIR AST module

samlang-cli/src/cli-service.ts, samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/mir-sources-lowering.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-demo/src/index.ts
=> [compiler][mir] Setup reference counting mode

samlang-core-ast/samlang-expressions.ts, samlang-core-checker/__tests__/expression-type-checker.test.ts, samlang-core-checker/__tests__/expression-type-fixer.test.ts, samlang-core-checker/__tests__/global-typing-context-builder.test.ts, samlang-core-checker/__tests__/index.test.ts, samlang-core-checker/__tests__/module-references-collector.test.ts, samlang-core-checker/__tests__/statement-type-checker.test.ts, samlang-core-checker/expression-type-checker.ts, samlang-core-checker/statement-type-checker.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-interpreter/__tests__/source-level-interpreter.test.ts, samlang-core-interpreter/source-level-interpreter.ts, samlang-core-parser/samlang-parser.ts, samlang-core-printer/__tests__/printer-source-level.test.ts, samlang-core-services/location-service.ts, samlang-core-services/variable-definition-service.ts
=> [ast] Rename source level AST constructors

samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-interpreter/__tests__/llvm-ir-interpreter.test.ts, samlang-core-interpreter/llvm-ir-interpreter.ts
=> [interpreter][llvm] Speed up LLVM tests

samlang-core-checker/__tests__/type-resolver.test.ts, samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-optimization/__tests__/control-flow-graph.test.ts, samlang-core-parser/__tests__/index.test.ts
=> [compiler][mir] Configurable `referenceCounting` flag in tests

samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/mir-sources-lowering.ts
=> [compiler][mir] Setup memory slot for reference counting

samlang-core-optimization/mir-common-subexpression-elimination-optimization.ts, samlang-core-optimization/mir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/mir-dead-code-elimination-optimization.ts, samlang-core-optimization/mir-inline-optimization.ts, samlang-core-optimization/mir-local-value-numbering-optimization.ts, samlang-core-optimization/mir-loop-algebraic-optimization.ts, samlang-core-optimization/mir-loop-induction-analysis.ts, samlang-core-optimization/mir-loop-induction-variable-elimination.ts, samlang-core-optimization/mir-loop-invariant-code-motion.ts, samlang-core-optimization/mir-loop-optimizations.ts, samlang-core-optimization/mir-loop-strength-reduction.ts, samlang-core-optimization/mir-optimization-common.ts, samlang-core-optimization/mir-tail-recursion-optimization.ts, samlang-core-optimization/mir-unused-name-elimination-optimization.ts
=> [compiler][mir][chore] Convert functions to named function format

.github/workflows/ci.yml, .gitignore, .yarn/plugins/@yarnpkg/plugin-monorail.cjs, .yarnrc.yml, package.json, yarn-plugin-monorail/build.js, yarn-plugin-monorail/package.json, yarn-plugin-monorail/src/compile.ts, yarn-plugin-monorail/src/plugin.ts, yarn-plugin-monorail/src/types.ts, yarn-plugin-monorail/src/utils/colors.ts, yarn-plugin-monorail/src/utils/spinner-progress.ts, yarn-plugin-monorail/src/utils/target-determinator.ts, yarn-plugin-monorail/src/utils/workspaces-json.ts, yarn-plugin-monorail/tsconfig.json, yarn.lock
This repo has more complicated dependency relationship and easier to test.
CI
=> [monorail] Move development of monorail in samlang repo

eslint-config-common/README.md, eslint-config-common/api.js, eslint-config-common/index.js, eslint-config-common/package.json, eslint-config-common/tsconfig.json, package.json, yarn.lock
=> [eslint] Move @dev-sam/eslint-config-common to samlang repo

samlang-core-ast/__tests__/mir-nodes.test.ts, samlang-core-ast/mir-nodes.ts
=> [ast][mir] Fix missing new line problem of struct init

.github/PULL_REQUEST_TEMPLATE.md
=> [repo] Slightly tweak test plan

samlang-cli/package.json, samlang-cli/src/cli-service.ts, samlang-core-optimization/index.ts, yarn.lock
=> [cli] Optimize MidIR in CLI

samlang-core-compiler/hir-expression-lowering.ts
=> [compiler][hir] Use `favoredTempVariable` to generate closer programs

samlang-core-ast/__tests__/hir-nodes.test.ts, samlang-core-ast/hir-nodes.ts, samlang-core-compiler/__tests__/hir-generics-specialization.test.ts, samlang-core-compiler/__tests__/hir-type-deduplication.test.ts, samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/hir-generics-specialization.ts, samlang-core-compiler/hir-type-deduplication.ts, samlang-core-compiler/mir-sources-lowering.ts
Goal is to move all the optimizations to HIR.
`yarn test`
=> [ast][hir] Introduce loop related statement nodes

samlang-core-optimization/__tests__/hir-tail-recursion-optimization.test.ts, samlang-core-optimization/__tests__/hir-unused-name-elimination-optimization.test.ts, samlang-core-optimization/hir-optimization-common.ts, samlang-core-optimization/hir-tail-recursion-optimization.ts, samlang-core-optimization/hir-unused-name-elimination-optimization.ts
=> [optimization] Migrate base optimizations to HIR

samlang-core-ast/__tests__/hir-flexible-op.test.ts, samlang-core-ast/hir-flexible-op.ts
=> [ast][hir] Migrate `flexible-op`

samlang-core-optimization/__tests__/hir-common-subexpression-elimination-optimization.test.ts, samlang-core-optimization/hir-common-subexpression-elimination-optimization.ts
=> [optimization] Migrate CSE optimization to HIR

samlang-core-optimization/__tests__/hir-loop-algebraic-optimization.test.ts, samlang-core-optimization/__tests__/hir-loop-induction-analysis.test.ts, samlang-core-optimization/__tests__/hir-loop-induction-variable-elimination.test.ts, samlang-core-optimization/__tests__/hir-loop-invariant-code-motion.test.ts, samlang-core-optimization/__tests__/hir-loop-optimizations.test.ts, samlang-core-optimization/__tests__/hir-loop-strength-reduction.test.ts, samlang-core-optimization/hir-loop-algebraic-optimization.ts, samlang-core-optimization/hir-loop-induction-analysis.ts, samlang-core-optimization/hir-loop-induction-variable-elimination.ts, samlang-core-optimization/hir-loop-invariant-code-motion.ts, samlang-core-optimization/hir-loop-optimizations.ts, samlang-core-optimization/hir-loop-strength-reduction.ts
=> [optimization] Migrate all loop optimizations to HIR

samlang-core-compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core-compiler/hir-toplevel-lowering.ts, samlang-core-integration-tests/__tests__/compiler-integration-test.test.ts, samlang-core-optimization/__tests__/index.test.ts, samlang-core-optimization/__tests__/mir-tail-recursion-optimization.test.ts, samlang-core-optimization/index.ts
=> [test] Do not test all variants of optimizations

samlang-core-optimization/hir-common-subexpression-elimination-optimization.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/hir-local-value-numbering-optimization.ts, samlang-core-optimization/hir-unused-name-elimination-optimization.ts
Leftovers of mass migration.
```
yarn test
```
=> [optimization] Rename `midIR` to `highIR`

samlang-core-ast/__tests__/mir-nodes.test.ts, samlang-core-ast/mir-nodes.ts, samlang-core-compiler/__tests__/llvm-sources-lowering.test.ts, samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/llvm-sources-lowering.ts, samlang-core-compiler/mir-sources-lowering.ts, samlang-core-optimization/__tests__/hir-loop-invariant-code-motion.test.ts
=> [compiler] Emit instructions that increase reference counting 

samlang-core-ast/__tests__/mir-nodes.test.ts, samlang-core-ast/mir-nodes.ts, samlang-core-compiler/__tests__/llvm-sources-lowering.test.ts, samlang-core-compiler/llvm-sources-lowering.ts, samlang-core-compiler/mir-sources-lowering.ts
=> [AST][optimization] Introduce `MIR_DEC_REF`

samlang-core-integration-tests/test-programs.ts
=> [test] Rename test case names for checked programs

samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/mir-sources-lowering.ts
=> [compiler][mir] Generate deref functions

samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/mir-sources-lowering.ts, samlang-demo/src/__test__/index.test.ts
=> [compiler][mir] Always create a function return collector for GC purpose

samlang-core-checker/expression-type-checker.ts, samlang-core-checker/module-type-checker.ts, samlang-core-checker/undefined-imports-checker.ts, samlang-core-optimization/hir-common-subexpression-elimination-optimization.ts, samlang-core-optimization/hir-conditional-constant-propagation-optimization.ts, samlang-core-optimization/hir-dead-code-elimination-optimization.ts, samlang-core-optimization/hir-inline-optimization.ts, samlang-core-optimization/hir-local-value-numbering-optimization.ts, samlang-core-optimization/hir-loop-induction-analysis.ts, samlang-core-optimization/hir-loop-invariant-code-motion.ts, samlang-core-optimization/hir-loop-strength-reduction.ts, samlang-core-services/language-service.ts, samlang-core-services/source-processor.ts, samlang-core-utils/__tests__/index.test.ts, samlang-core-utils/index.ts
=> [util] Introduce filterMap util

samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/mir-sources-lowering.ts, samlang-demo/src/__test__/index.test.ts
=> [compiler][mir] Correctly implement decRef function for closure types

samlang-cli/src/cli-service.ts
=> [cli] Reduce number of files emitted

samlang-core-ast/__tests__/mir-nodes.test.ts, samlang-core-ast/mir-nodes.ts, samlang-core-compiler/__tests__/llvm-sources-lowering.test.ts, samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/llvm-sources-lowering.ts, samlang-core-compiler/mir-sources-lowering.ts
=> [ast][compiler] Do not special-case zero RC check for `MIR_INC_REF`

samlang-core-ast/__tests__/hir-nodes.test.ts, samlang-core-ast/hir-nodes.ts, samlang-core-compiler/__tests__/hir-expression-lowering.test.ts, samlang-core-compiler/__tests__/hir-generics-specialization.test.ts, samlang-core-compiler/__tests__/hir-type-deduplication.test.ts, samlang-core-optimization/__tests__/hir-conditional-constant-propagation-optimization.test.ts, samlang-core-optimization/__tests__/hir-dead-code-elimination-optimization.test.ts, samlang-core-optimization/__tests__/hir-inline-optimization.test.ts, samlang-core-optimization/__tests__/hir-local-value-numbering-optimization.test.ts, samlang-core-optimization/__tests__/hir-loop-invariant-code-motion.test.ts
=> [ast][hir] Simplify closure-init pretty-printing syntax

samlang-core-ast/__tests__/mir-nodes.test.ts, samlang-core-ast/mir-nodes.ts, samlang-core-compiler/__tests__/mir-sources-lowering.test.ts
=> [ast][mir] Unify pretty-printing code

samlang-cli/src/cli-service.ts, samlang-core-ast/__tests__/mir-nodes.test.ts, samlang-core-ast/mir-nodes.ts, samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-demo/src/__test__/index.test.ts, scripts/compile-repository.ts
=> [ast] Pretty-print MIR sources as either JS or TS

samlang-core-compiler/mir-sources-lowering.ts
=> [compiler][mir] Parameterize `isSameAsAnyType`

samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/mir-sources-lowering.ts
=> [compiler][mir] Avoid cast when string destructor is expected

samlang-core-compiler/__tests__/mir-sources-lowering.test.ts, samlang-core-compiler/mir-sources-lowering.ts, samlang-demo/src/__test__/index.test.ts
=> [compiler][mir] Avoid collectors if variables are not reference typed

samlang-core-ast/wasm-nodes.ts
=> [ast] Setup type definition for WASM nodes

samlang-core/parser/__tests__/index.test.ts, samlang-core/parser/samlang-parser.ts
=> [parser] Parse optional class member type arguments

.github/workflows/ci.yml
=> [ci] Fix CI config to use auto cache path

samlang-vscode/package.json, samlang-vscode/src/extension.ts
=> [vscode] Increase stack limit

samlang-core/compiler/hir-toplevel-lowering.ts
=> [compiler] Simple cleanup

samlang-core/ast/samlang-nodes.ts, samlang-core/compiler/hir-toplevel-lowering.ts
=> [compiler] Split function compiler and method compiler

.github/workflows/ci.yml, package.json, samlang-vscode/README.md, samlang-vscode/package.json, samlang-vscode/src/extension.ts
=> [repo] Adopt `setup-node-project` from infra repo

samlang-core/ast/__tests__/mir-nodes.test.ts, samlang-core/ast/__tests__/printer-js.test.ts, samlang-core/ast/mir-nodes.ts, samlang-core/interpreter/__tests__/expression-interpreter.test.ts, samlang-core/interpreter/__tests__/module-interpreter.test.ts, samlang-core/interpreter/expression-interpreter.ts, samlang-core/interpreter/module-interpreter.ts
During recent refactors, a lot of high quality tests have been lost due to infra changes. However, they represent an important part of the history of the repo, and no infra changes can justify removing them.
This PR restores these important tests. They deserve to be remembered and honored forever.
```
pnpm test
```
=> [repo] Restore important tests

package.json, pnpm-lock.yaml, samlang-cli/package.json, samlang-core/package.json
=> [release] Include all source files in NPM release

samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/__tests__/statement-type-checker.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/__tests__/undefined-import-checker.test.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/module-type-checker.ts, samlang-core/checker/typing-context.ts, samlang-core/checker/undefined-imports-checker.ts, samlang-core/compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core/compiler/__tests__/hir-type-conversion.test.ts, samlang-core/compiler/hir-toplevel-lowering.ts, samlang-core/compiler/hir-type-conversion.ts, samlang-core/interpreter/__tests__/module-interpreter.test.ts, samlang-core/interpreter/module-interpreter.ts, samlang-core/parser/__tests__/index.test.ts, samlang-core/parser/samlang-parser.ts, samlang-core/printer/index.ts, samlang-core/printer/printer-source-level.ts, samlang-core/services/api.ts, samlang-core/services/location-service.ts
=> [ast] Use SourceId for more toplevel constructs

samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/__tests__/undefined-import-checker.test.ts, samlang-core/checker/undefined-imports-checker.ts, samlang-core/compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core/interpreter/__tests__/module-interpreter.test.ts, samlang-core/parser/samlang-parser.ts, samlang-core/services/variable-definition-service.ts
=> [ast] Add interfaces to AST

samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/module-type-checker.ts, samlang-core/services/__tests__/api.test.ts
=> [checker] Enforce interface toplevel validity

samlang-core/checker/module-type-checker.ts, samlang-core/checker/typing-context.ts
=> [checker] More principled name collision checker

samlang-core/checker/module-type-checker.ts
=> [checker] Centralize name collision detection in top level checker

samlang-core/checker/index.ts, samlang-core/checker/module-type-checker.ts
=> [checker] Convert module checker to use functions

samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/__tests__/statement-type-checker.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/constraint-aware-checker.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/index.ts, samlang-core/checker/module-type-checker.ts, samlang-core/checker/typing-context.ts, samlang-core/parser/samlang-parser.ts, samlang-core/services/__tests__/api.test.ts, samlang-core/services/api.ts
=> [checker] Include interfaces in global typing context

samlang-core/parser/samlang-parser.ts, samlang-core/printer/__tests__/printer-source-level.test.ts, samlang-core/printer/index.ts, samlang-core/printer/printer-source-level.ts
=> [printer] Pretty print interfaces

samlang-core/checker/module-type-checker.ts, samlang-core/checker/toplevel-name-collision-checker.ts
=> [checker] Move toplevel name collision checkers to its own file

samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/__tests__/statement-type-checker.test.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/module-type-checker.ts, samlang-core/checker/ssa-analysis.ts, samlang-core/checker/statement-type-checker.ts
=> [checker] Use SSA builder to check name resolution and collision

samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/module-type-checker.ts, samlang-core/checker/ssa-analysis.ts, samlang-core/checker/typing-context.ts
=> [checker] Switch to location based environment

samlang-core/ast/common-nodes.ts, samlang-core/checker/__tests__/expression-type-fixer.test.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/expression-type-fixer.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/compiler/hir-expression-lowering.ts, samlang-core/compiler/hir-type-conversion.ts, samlang-core/parser/samlang-parser.ts, samlang-core/services/location-service.ts
=> [checker] Produce more accurate reasons

samlang-core/__tests__/utils.test.ts, samlang-core/ast/__tests__/common-nodes.test.ts, samlang-core/ast/common-nodes.ts, samlang-core/ast/types.d.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/__tests__/module-references-collector.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/__tests__/undefined-import-checker.test.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/index.ts, samlang-core/checker/ssa-analysis.ts, samlang-core/checker/typing-context.ts, samlang-core/compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core/optimization/hir-common-subexpression-elimination-optimization.ts, samlang-core/services/__tests__/variable-definition-service.test.ts, samlang-core/services/api.ts, samlang-core/services/location-service.ts, samlang-core/services/variable-definition-service.ts, samlang-core/utils.ts
=> [util] Kill Hashable interface and switch to functor like solution

samlang-core/compiler/__tests__/hir-expression-lowering.test.ts, samlang-core/compiler/hir-expression-lowering.ts
=> [compiler][hir] Remove some special casing for void return

samlang-core/ast/samlang-nodes.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/module-references-collector.ts, samlang-core/parser/samlang-parser.ts, samlang-core/printer/printer-source-level.ts
=> [ast] Make type annotation node optional

samlang-core/ast/__tests__/samlang-nodes.test.ts, samlang-core/ast/samlang-nodes.ts, samlang-core/compiler/hir-type-conversion.ts
=> [ast][type] Introduce unknown type

samlang-core/checker/__tests__/contextual-type-meet.test.ts, samlang-core/checker/contextual-type-meet.ts
=> [checker] Support meet operation with contextual typing

samlang-core/__tests__/errors.test.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/errors.ts
=> [errors] Introduce general `ArityMismatchError`

samlang-core/checker/__tests__/contextual-type-meet.test.ts, samlang-core/checker/__tests__/type-constraint-solver.test.ts, samlang-core/checker/contextual-type-meet.ts, samlang-core/checker/type-constraints-solver.ts
=> [checker] Generic type constraint solver

samlang-core/checker/__tests__/function-call-type-checker.test.ts, samlang-core/checker/function-call-type-checker.ts
=> [checker] Bidirectional function call type checking

samlang-core/checker/__tests__/function-call-type-checker.test.ts, samlang-core/checker/function-call-type-checker.ts
=> [checker] Make function call checker take optional return type hint

samlang-core/checker/__tests__/contextual-type-meet.test.ts, samlang-core/checker/__tests__/function-call-type-checker.test.ts, samlang-core/checker/__tests__/type-constraint-solver.test.ts, samlang-core/checker/contextual-type-meet.ts, samlang-core/checker/function-call-type-checker.ts
=> [checker] Move constraint solving closer to contextual typing needs

samlang-core/checker/__tests__/type-constraint-solver.test.ts, samlang-core/checker/function-call-type-checker.ts, samlang-core/checker/type-constraints-solver.ts
=> [checker] More flexible constraint solver

samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/function-call-type-checker.ts, samlang-core/checker/typing-context.ts
=> [checker] Use reposition function more extensively

package.json, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/parser/__tests__/index.test.ts, samlang-core/parser/samlang-parser.ts, samlang-core/printer/__tests__/printer-source-level.test.ts, samlang-core/printer/printer-source-level.ts, samlang-core/test-programs.ts, tests/DifferentExpressionDemo.sam, tests/DifferentModulesDemo.sam, tests/StdLib.sam
=> [parser] Change type argument syntax to align with most languages

samlang-core/ast/__tests__/samlang-nodes.test.ts, samlang-core/ast/common-nodes.ts, samlang-core/checker/contextual-type-meet.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/function-call-type-checker.ts, samlang-core/checker/ssa-analysis.ts, samlang-core/checker/type-constraints-solver.ts, samlang-core/compiler/hir-type-conversion.ts, samlang-core/parser/samlang-parser.ts
=> [ast] Fix naming of locations in reason

samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/function-call-type-checker.test.ts, samlang-core/checker/__tests__/module-references-collector.test.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/function-call-type-checker.ts, samlang-core/checker/module-references-collector.ts, samlang-core/checker/ssa-analysis.ts, samlang-core/compiler/__tests__/hir-expression-lowering.test.ts, samlang-core/compiler/hir-expression-lowering.ts, samlang-core/interpreter/__tests__/expression-interpreter.test.ts, samlang-core/interpreter/expression-interpreter.ts, samlang-core/interpreter/module-interpreter.ts, samlang-core/parser/samlang-parser.ts, samlang-core/printer/printer-source-level.ts, samlang-core/services/variable-definition-service.ts
Instead of using unknown as placeholder
Title
```
pnpm test
```
=> [ast] Represent optional lambda annotation in AST

samlang-core/ast/__tests__/samlang-nodes.test.ts, samlang-core/ast/samlang-nodes.ts, samlang-core/checker/contextual-type-meet.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/function-call-type-checker.ts, samlang-core/checker/module-references-collector.ts, samlang-core/checker/ssa-analysis.ts, samlang-core/checker/type-constraints-solver.ts, samlang-core/checker/type-substitution.ts, samlang-core/checker/typing-context.ts, samlang-core/compiler/hir-expression-lowering.ts, samlang-core/compiler/hir-type-conversion.ts, samlang-core/interpreter/__tests__/expression-interpreter.test.ts, samlang-core/interpreter/__tests__/module-interpreter.test.ts, samlang-core/parser/samlang-parser.ts, samlang-core/services/api.ts
=> [ast] Factor out unknown type to its own kind

samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/__tests__/type-substitution.test.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/services/__tests__/api.test.ts
=> [checker] Do not normalize member type information

samlang-core/checker/__tests__/contextual-type-meet.test.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/function-call-type-checker.test.ts, samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/__tests__/type-constraint-solver.test.ts, samlang-core/checker/__tests__/undefined-import-checker.test.ts, samlang-core/checker/contextual-type-meet.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/function-call-type-checker.ts, samlang-core/checker/index.ts, samlang-core/checker/module-type-checker.ts, samlang-core/checker/ssa-analysis.ts, samlang-core/checker/type-constraints-solver.ts, samlang-core/checker/undefined-imports-checker.ts, samlang-core/errors.ts, samlang-core/parser/__tests__/index.test.ts, samlang-core/parser/__tests__/samlang-lexer.test.ts, samlang-core/parser/__tests__/samlang-parser.test.ts, samlang-core/parser/index.ts, samlang-core/parser/samlang-lexer.ts, samlang-core/parser/samlang-parser.ts, samlang-core/printer/__tests__/printer-source-level.test.ts, samlang-core/services/__tests__/variable-definition-service.test.ts, samlang-core/services/api.ts
=> [errors] Eliminate ModuleErrorCollector

samlang-core/errors.ts
=> [errors][EZ] Do not import type from dist

.github/workflows/ci.yml, jest-esbuild-transformer/package.json, package.json, pnpm-lock.yaml, samlang-cli/package.json, samlang-core/package.json, samlang-vscode/package.json, turbo.json
=> [dependency] Bump pnpm

package.json, pnpm-lock.yaml, samlang-core/checker/interface-conformance-checking.ts
=> [checker] Bootstrap Conformance checking

samlang-core/__tests__/errors.test.ts, samlang-core/errors.ts
=> [errors] Refactor error reporting and add `MissingDefinitionsError`

samlang-core/checker/interface-conformance-checking.ts
=> [checker] Error on missing definitions

samlang-core/ast/samlang-nodes.ts, samlang-core/parser/__tests__/index.test.ts, samlang-core/parser/samlang-parser.ts
=> [parser] Parse implements node

configurations/tsconfig.base.json, jest-esbuild-transformer/api.js, jest-esbuild-transformer/index.js, jest-esbuild-transformer/package.json, package.json, pnpm-lock.yaml, samlang-cli/src/__tests__/cli.test.ts, samlang-cli/src/__tests__/configuration.test.ts, samlang-core/__tests__/loader.test.ts, samlang-core/__tests__/printer-integration-test.test.ts, samlang-core/compiler/index.ts
=> [esr] Improve jest transform

samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/typing-context.ts
=> [checker] Track implements type in global typing context

samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/typing-context.ts, samlang-core/parser/samlang-parser.ts
=> [ast] Rename `implementsNode` to `extendsOrImplementsNode`

samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/ssa-analysis.ts
=> [checker] Validate extends or implements node in SSA analysis

jest-esbuild-transformer/api.js, jest-esbuild-transformer/index.js
=> [jest-transformer] Cache per-file transpilation result

samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/typing-context.ts
Compute this so we can use the context to check conformance.
```
pnpm test
```
=> [checker] Compute fully inlined interface context

samlang-core/checker/interface-conformance-checking.ts
=> [checker] Fix repo

samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/interface-conformance-checking.ts, samlang-core/checker/typing-context.ts
=> [checker] First iteration of interface conformance checking

samlang-core/checker/module-type-checker.ts
=> [checker] Don't access this type in interface method

samlang-core/checker/ssa-analysis.ts
=> [checker][ssa] Visit `extendsOrImplementsNode` under tparams context

samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/index.ts, samlang-core/checker/interface-conformance-checking.ts
=> [checker] Bug fixes and tests for conformance check

samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/typing-context.ts
=> [checker] Detect cyclic subtyping

samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/interface-conformance-checking.ts, samlang-core/checker/typing-context.ts
=> [checker] Return instead of throwing cyclic type

samlang-core/__tests__/errors.test.ts, samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/interface-conformance-checking.ts, samlang-core/errors.ts
=> [checker] Error on cyclic class/interfaces

samlang-core/ast/__tests__/samlang-nodes.test.ts, samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/function-call-type-checker.test.ts, samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/__tests__/type-constraint-solver.test.ts, samlang-core/checker/__tests__/type-substitution.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/function-call-type-checker.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/interface-conformance-checking.ts, samlang-core/checker/module-type-checker.ts, samlang-core/checker/ssa-analysis.ts, samlang-core/checker/type-constraints-solver.ts, samlang-core/checker/type-substitution.ts, samlang-core/checker/typing-context.ts, samlang-core/compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core/compiler/__tests__/hir-type-conversion.test.ts, samlang-core/compiler/hir-expression-lowering.ts, samlang-core/compiler/hir-generics-specialization.ts, samlang-core/compiler/hir-toplevel-lowering.ts, samlang-core/compiler/hir-type-conversion.ts, samlang-core/interpreter/__tests__/module-interpreter.test.ts, samlang-core/parser/__tests__/index.test.ts, samlang-core/parser/samlang-parser.ts, samlang-core/printer/index.ts, samlang-core/printer/printer-source-level.ts, samlang-core/services/api.ts
=> [ast][checker] Initial cut of bounded generics

samlang-core/ast/__tests__/samlang-nodes.test.ts, samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/index.test.ts, samlang-core/parser/__tests__/index.test.ts, samlang-core/parser/samlang-parser.ts
=> [parser] Restrict bound type to be id type

.gitignore
=> [chore] Ignore logs

samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/index.ts, samlang-core/checker/interface-conformance-checking.ts, samlang-core/checker/module-type-checker.ts, samlang-core/checker/typing-context.ts, samlang-core/compiler/wasm-module-lowering.ts, samlang-core/services/api.ts
=> [repo] Refactors to prepare for optimizing context

jest-esbuild-transformer/api.js, samlang-cli/src/configuration.ts, samlang-core/compiler/__tests__/hir-expression-lowering.test.ts, samlang-core/compiler/hir-expression-lowering.ts, samlang-core/compiler/hir-generics-specialization.ts, samlang-core/compiler/hir-toplevel-lowering.ts, samlang-core/compiler/mir-sources-lowering.ts
=> [repo] Migrate dictionaries to maps

samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/__tests__/interface-conformance-checking.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/index.ts, samlang-core/checker/interface-conformance-checking.ts, samlang-core/checker/module-type-checker.ts, samlang-core/checker/typing-context.ts, samlang-core/services/api.ts, samlang-core/services/location-service.ts, samlang-core/utils.ts
=> [checker] Optimize global typing context

samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/index.ts, samlang-core/checker/typing-context.ts
=> [checker] Move around DEFAULT_BUILTIN_TYPING_CONTEXT

samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/global-typing-context-builder.ts
=> [checker] Perform type substitution on the method tparam bound

samlang-core/__tests__/errors.test.ts, samlang-core/ast/__tests__/samlang-nodes.test.ts, samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/contextual-type-meet.test.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/function-call-type-checker.test.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/__tests__/module-references-collector.test.ts, samlang-core/checker/__tests__/type-constraint-solver.test.ts, samlang-core/checker/__tests__/type-substitution.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/type-substitution.ts, samlang-core/compiler/__tests__/hir-expression-lowering.test.ts, samlang-core/compiler/__tests__/hir-toplevel-lowering.test.ts, samlang-core/compiler/__tests__/hir-type-conversion.test.ts, samlang-core/interpreter/__tests__/expression-interpreter.test.ts, samlang-core/interpreter/__tests__/module-interpreter.test.ts, samlang-core/printer/__tests__/printer-source-level.test.ts
=> [ast] Create `AstBuilder` for easier test AST construction

samlang-core/__tests__/errors.test.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/__tests__/index.test.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/errors.ts
=> [checker] Simpler conformance check with bounded generics

samlang-core/ast/samlang-nodes.ts, samlang-core/checker/__tests__/expression-type-checker.test.ts, samlang-core/checker/__tests__/function-call-type-checker.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/module-type-checker.ts, samlang-core/checker/typing-context.ts
=> [checker] Support subtyping check in global context

samlang-core/__tests__/errors.test.ts, samlang-core/checker/__tests__/function-call-type-checker.test.ts, samlang-core/checker/__tests__/global-typing-context-builder.test.ts, samlang-core/checker/expression-type-checker.ts, samlang-core/checker/function-call-type-checker.ts, samlang-core/checker/global-typing-context-builder.ts, samlang-core/checker/typing-context.ts, samlang-core/errors.ts
=> [checker] Validate type arguments at function call

samlang-core/__tests__/errors.test.ts, samlang-core/checker/__tests__/main-type-checker.test.ts, samlang-core/checker/__tests__/typing-context.test.ts, samlang-core/checker/main-type-checker.ts, samlang-core/checker/typing-context.ts, samlang-core/errors.ts
Post LTI, a lot of resolution can be simplified as we can drop some restrictions.
```
pnpm test
```
=> [checker] Simplify the resolution of type definitions

samlang-core/ast/common-names.ts, samlang-core/compiler/hir-toplevel-lowering.ts, samlang-core/compiler/hir-type-conversion.ts, samlang-core/printer/__tests__/printer-source-level.test.ts, samlang-core/printer/index.ts, tests/AllTests.sam
A bunch of easy cleanups before figuring our a potential GC bug
=> [misc] Cleanups for bounded generics

package.json, pnpm-lock.yaml, samlang-core/__tests__/main.test.ts, samlang-core/ast/__tests__/mir-nodes.test.ts, samlang-core/ast/mir-nodes.ts, samlang-core/compiler/__tests__/mir-sources-lowering.test.ts, samlang-core/compiler/mir-sources-lowering.ts, samlang-core/compiler/wasm-module-lowering.ts, samlang-core/test-programs.ts, samlang-vscode/syntaxes/samlang.json, tests/AllTests.sam, tests/SortableList.sam, tests/snapshot.txt
We need to increase the ref count after collecting function returns
=> [compiler][mir] Fix use-after-free GC bug

.gitignore, Cargo.toml, crates/samlang-cli/Cargo.toml, crates/samlang-core/src/ast/common_names.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-wasm/bundle.cjs, crates/samlang-wasm/lazy-index.js, crates/samlang-wasm/loader.js, crates/samlang-wasm/setup-generated-package.sh, crates/samlang-wasm/src/lib.rs, crates/samlang-wasm/test-samlang-wasm.mjs, package.json, pnpm-lock.yaml
The generated package is intended to be manually synced to my website repo, and it can be easily integrated together with monaco editor on the web. Demo:
=> [wasm-target] Produce easier to work with wasm code

.github/workflows/validate.yml, .vscode/settings.json, benchmark.sh, crates/samlang-cli/src/main.rs, crates/samlang-core/src/checker/global_typing_context_builder.rs
Make it repeat in the CLI rather than Bash to avoid repeating loading cost that doesn't tell much about performance
=> [repo] More accurate benchmark on actual performance

.vscode/settings.json, crates/samlang-cli/src/main.rs, crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/ssa_analysis_tests.rs, crates/samlang-core/src/checker/typing_context.rs, crates/samlang-core/src/checker/typing_context_tests.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/parser.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/printer/prettier.rs, crates/samlang-core/src/printer/source_printer.rs, crates/samlang-core/src/services/location_cover.rs, crates/samlang-core/src/services/variable_definition.rs, stdlib/utils.sam, tests/AllTests.sam, tests/AndOrInsideIf.sam, tests/Benchmark.sam, tests/BlockInIfElse.sam, tests/CSETest.sam, tests/ConstantFoldingTest.sam, tests/DevMeggo.sam, tests/DifferentExpressionDemo.sam, tests/DifferentModulesDemo.sam, tests/GC.sam, tests/LoopOptimization.sam, tests/MathFunctions.sam, tests/PrintHelloWorld.sam, tests/SortableList.sam, tests/StdLib.sam
=> [parser][format] Parser & Printer Improvements

.gitignore, crates/samlang-cli/src/main.rs, crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs, crates/samlang-core/src/checker.rs, crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/global_typing_context_builder.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/ssa_analysis.rs, crates/samlang-core/src/checker/ssa_analysis_tests.rs, crates/samlang-core/src/checker/typing_context.rs, crates/samlang-core/src/checker/typing_context_tests.rs, crates/samlang-core/src/checker/undefined_imports_checker.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/interpreter.rs, crates/samlang-core/src/interpreter/source_interpreter.rs, crates/samlang-core/src/parser.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/printer.rs, crates/samlang-core/src/printer/source_printer.rs, crates/samlang-core/src/services/api.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/gc.rs, crates/samlang-core/src/services/location_cover.rs, crates/samlang-core/src/services/variable_definition.rs
[ast] Setup polymorphic AST
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/942).
* __->__ #942
=> [ast] Setup polymorphic AST

crates/samlang-cli/src/main.rs, crates/samlang-core/src/checker.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/errors.rs, crates/samlang-core/src/services/api.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/dep_graph.rs, packages/samlang-vscode/package.json, pnpm-lock.yaml
[service] Incremental recheck in services
With all the previous preparations, it's time to make the LSP correctly incrementally recheck sources again!
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/952).
* #953
* __->__ #952
=> [service] Incremental recheck in services

crates/samlang-cli/src/main.rs, crates/samlang-core/src/checker.rs, crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/global_signature.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/type_.rs, crates/samlang-core/src/checker/typing_context.rs, crates/samlang-core/src/checker/typing_context_tests.rs, crates/samlang-core/src/errors.rs, crates/samlang-core/src/services/api.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/dep_graph.rs, packages/samlang-vscode/package.json, pnpm-lock.yaml
[checker] Merge interface signature and type definition
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/953).
* __->__ #953
* #952
=> [checker] Merge interface signature and type definition

crates/samlang-cli/src/main.rs, crates/samlang-core/src/services.rs, crates/samlang-core/src/services/api.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/global_searcher.rs, crates/samlang-core/src/services/location_cover.rs, crates/samlang-core/src/services/variable_definition.rs
This is an initial implementation with most of the functionality. Currently, this is still fairly inefficient, since it requires O(repo) search. We can optimize it further in the future, when samlang codebase has grown to some significant size.
=> [services] Global find references

crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/typing_context.rs, crates/samlang-core/src/checker/typing_context_tests.rs, crates/samlang-core/src/errors.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/services/api.rs
[checker][fix] Ban accessing interface functions directly
=> [checker][fix] Ban accessing interface functions directly

crates/samlang-core/src/services/api.rs, crates/samlang-core/src/services/api_tests.rs
[lsp] Pretty printer for results
=> [lsp] Pretty printer for results

crates/samlang-cli/src/main.rs, crates/samlang-core/src/services.rs, crates/samlang-core/src/services/api.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/location_cover.rs, crates/samlang-core/src/services/server_state.rs, crates/samlang-wasm/src/lib.rs
[lsp] Split state and services
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/965).
* #967
* #966
* __->__ #965
=> [lsp] Split state and services

crates/samlang-cli/src/main.rs, crates/samlang-core/src/services/api.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/location_cover.rs
[lsp] Support signature help
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/966).
* #967
* __->__ #966
=> [lsp] Support signature help

crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs
This is a necessary step to prepare fine-grained AST diffing.
=> [ast] Derive eq for all source ast nodes

crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/printer/source_printer.rs, crates/samlang-core/src/services/ast_differ.rs
[ast][source] Keep track of comments' locations
=> [ast][source] Keep track of comments' locations

.cargo/config.toml, crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/typing_context.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/interpreter/source_interpreter.rs, crates/samlang-core/src/optimization/inlining_tests.rs, crates/samlang-core/src/parser/lexer.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/printer.rs, crates/samlang-core/src/printer/prettier.rs, crates/samlang-core/src/printer/source_printer.rs, crates/samlang-core/src/services/ast_differ.rs, crates/samlang-core/src/services/server_state.rs, crates/samlang-core/src/services/variable_definition.rs
[service][differ] Setup diffing infra and implements imports and toplevel diffing
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/973).
* #976
* #975
* #974
* __->__ #973
=> [service][differ] Setup diffing infra and implements imports and toplevel diffing

crates/samlang-cli/src/main.rs, crates/samlang-core/src/ast/loc.rs, crates/samlang-core/src/common.rs, crates/samlang-core/src/services/api.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/ast_differ.rs
[service] Use ast differ to power auto imports
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/975).
* #976
* __->__ #975
=> [service] Use ast differ to power auto imports

crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/printer/source_printer.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/ast_differ.rs, tests/AllTests.sam, tests/AndOrInsideIf.sam, tests/Benchmark.sam, tests/CSETest.sam, tests/ConstantFoldingTest.sam, tests/DifferentExpressionDemo.sam, tests/DifferentModulesDemo.sam, tests/EvaluationOrder.sam, tests/GC.sam, tests/IntToString.sam, tests/LoopOptimization.sam, tests/MathFunctions.sam, tests/SortableList.sam
[parser][printer] Allow semicolon after import
=> [parser][printer] Allow semicolon after import

crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/checker_utils.rs, crates/samlang-core/src/checker/checker_utils_tests.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/ssa_analysis_tests.rs, crates/samlang-core/src/checker/type_.rs, crates/samlang-core/src/checker/typing_context.rs, crates/samlang-core/src/checker/typing_context_tests.rs, crates/samlang-core/src/compiler/hir_type_conversion.rs, crates/samlang-core/src/services/gc.rs, crates/samlang-core/src/services/location_cover.rs
=> [checker] Separate any and placeholder type

.cargo/config.toml, crates/samlang-core/src/ast/hir.rs, crates/samlang-core/src/ast/hir_tests.rs, crates/samlang-core/src/compiler.rs, crates/samlang-core/src/compiler/hir_constant_param_elimination.rs, crates/samlang-core/src/compiler/hir_lowering.rs, package.json
This optimization prepares us to unify function call and method call, since the optimization can rewrite away the redundancies.
=> [optimization] Constant param elimination

package.json
[repo] Cleanup target before running tests
=> [repo] Cleanup target before running tests

crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/global_signature.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/typing_context.rs, crates/samlang-core/src/checker/typing_context_tests.rs, crates/samlang-core/src/errors.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/services/server_state.rs, package.json
[checker] Ban functions in interfaces
=> [checker] Ban functions in interfaces

crates/samlang-core/src/ast/hir.rs, crates/samlang-core/src/ast/hir_tests.rs, crates/samlang-core/src/compiler/hir_constant_param_elimination.rs, crates/samlang-core/src/compiler/hir_generics_specialization.rs, crates/samlang-core/src/compiler/hir_type_deduplication.rs, crates/samlang-core/src/compiler/mir_lowering.rs, crates/samlang-core/src/optimization/common_subexpression_elimination.rs, crates/samlang-core/src/optimization/conditional_constant_propagation.rs, crates/samlang-core/src/optimization/conditional_constant_propagation_tests.rs, crates/samlang-core/src/optimization/dead_code_elimination.rs, crates/samlang-core/src/optimization/dead_code_elimination_tests.rs, crates/samlang-core/src/optimization/inlining.rs, crates/samlang-core/src/optimization/inlining_tests.rs, crates/samlang-core/src/optimization/local_value_numbering.rs, crates/samlang-core/src/optimization/local_value_numbering_tests.rs, crates/samlang-core/src/optimization/loop_induction_analysis.rs, crates/samlang-core/src/optimization/loop_induction_variable_elimination.rs, crates/samlang-core/src/optimization/loop_invariant_code_motion.rs, crates/samlang-core/src/optimization/loop_optimizations.rs, crates/samlang-core/src/optimization/unused_name_elimination.rs
This is needed to support flexible and optimized layout of non-uniform variants.
=> [hir] Introduce cast statement

crates/samlang-core/src/ast/common_names.rs, crates/samlang-core/src/ast/hir.rs, crates/samlang-core/src/ast/hir_tests.rs, crates/samlang-core/src/compiler/hir_generics_specialization.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/compiler/hir_type_conversion.rs, crates/samlang-core/src/compiler/hir_type_deduplication.rs, crates/samlang-core/src/compiler/mir_lowering.rs, crates/samlang-core/src/optimization/unused_name_elimination.rs
[compiler][hir] True non-uniform variants
=> [compiler][hir] True non-uniform variants

crates/samlang-core/src/ast/hir.rs, crates/samlang-core/src/ast/lir.rs, crates/samlang-core/src/ast/mir.rs
[ast] Avoid string creation
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1008).
* #1010
* #1009
* __->__ #1008
=> [ast] Avoid string creation

crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/errors.rs
[error] Store more information as PStr
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1010).
* #1013
* #1012
* #1011
* __->__ #1010
=> [error] Store more information as PStr

crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/type_.rs, crates/samlang-core/src/common.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/compiler/lir_lowering.rs, crates/samlang-core/src/errors.rs, crates/samlang-core/src/optimization/loop_algebraic_optimization.rs
[perf] more compact PStr
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1011).
* #1013
* #1012
* __->__ #1011
* #1010
=> [perf] more compact PStr

Cargo.lock, crates/samlang-core/Cargo.toml, crates/samlang-core/src/parser/lexer.rs
[perf] Use compile time keyword hashtable
=> [perf] Use compile time keyword hashtable

crates/samlang-core/src/ast/mir.rs, crates/samlang-core/src/ast/mir_tests.rs, crates/samlang-core/src/compiler/lir_lowering.rs, crates/samlang-core/src/compiler/mir_generics_specialization.rs, crates/samlang-core/src/compiler/mir_type_deduplication.rs, crates/samlang-core/src/optimization/unused_name_elimination.rs
=> [compiler][mir] Generate optimized enum representation

crates/samlang-core/src/compiler/mir_generics_specialization.rs, crates/samlang-core/src/integration_tests.rs
[compiler][mir] Fix incorrect assumption of unboxed optimization
=> [compiler][mir] Fix incorrect assumption of unboxed optimization

samlang-dev, stdlib/utils.sam, tests/DifferentExpressionDemo.sam
[lib] Make use of optimized enum representation
=> [lib] Make use of optimized enum representation

crates/samlang-cli/src/main.rs, crates/samlang-core/src/ast.rs, crates/samlang-core/src/ast/reason.rs, crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/global_signature.rs, crates/samlang-core/src/checker/type_.rs, crates/samlang-core/src/checker/typing_context.rs, crates/samlang-core/src/checker/typing_context_tests.rs, crates/samlang-core/src/compiler/lir_unused_name_elimination.rs, crates/samlang-core/src/errors.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/lib.rs, crates/samlang-core/src/optimization/unused_name_elimination.rs, crates/samlang-core/src/parser.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/printer/source_printer.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/global_searcher.rs, crates/samlang-core/src/services/location_cover.rs, crates/samlang-core/src/services/server_state.rs, crates/samlang-wasm/lazy-index.js, crates/samlang-wasm/setup-generated-package.sh, crates/samlang-wasm/src/lib.rs, crates/samlang-wasm/test-samlang-wasm.mjs
This diff updates the current error printing infra to support
- Printing different errors for different platforms (text, terminal, ide)
- Multi-line errors
- Code frames
=> [error] Error printing revamp

crates/samlang-core/src/ast/reason.rs, crates/samlang-core/src/errors.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/server_state.rs
[error] Connect stacked error to new error printing infra
=> [error] Connect stacked error to new error printing infra

crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/type_system.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/lib.rs, crates/samlang-core/src/services/server_state.rs
Avoiding those that make heavy use of contextual typing intact for now, but deal with some easy ones first.
=> [checker] Connect new type system implementation to part of the type checker

crates/samlang-core/src/ast/reason.rs, crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/typing_context.rs, crates/samlang-core/src/checker/typing_context_tests.rs, crates/samlang-core/src/errors.rs, crates/samlang-core/src/integration_tests.rs
Partially address #1043
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1044).
* #1047
* #1046
* #1045
* __->__ #1044
=> [checker] Remove most of pretty printing required for error messages

crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/ssa_analysis.rs, crates/samlang-core/src/checker/ssa_analysis_tests.rs, crates/samlang-core/src/checker/typing_context.rs
[checker] Stop depend on casing for capture analysis
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1046).
* #1047
* __->__ #1046
=> [checker] Stop depend on casing for capture analysis

Cargo.toml, crates/samlang-core/src/ast/source_tests.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/optimization/loop_algebraic_optimization.rs
[chore] Fix lint after rust upgrade
=> [chore] Fix lint after rust upgrade

crates/samlang-core/src/checker.rs, crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/interpreter/source_interpreter.rs, crates/samlang-core/src/lib.rs, crates/samlang-core/src/services/api.rs, crates/samlang-core/src/services/gc.rs, crates/samlang-core/src/services/global_searcher.rs, crates/samlang-core/src/services/location_cover.rs, crates/samlang-core/src/services/server_state.rs
[checker] Remove checker's read dependency on heap
=> [checker] Remove checker's read dependency on heap

stdlib/utils.sam, tests/SortableList.sam
[stdlib] Add more tuple types
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1050).
* #1056
* #1055
* #1054
* #1053
* #1052
* #1051
* __->__ #1050
=> [stdlib] Add more tuple types

crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/ssa_analysis.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/interpreter/source_interpreter.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/printer/source_printer.rs, crates/samlang-core/src/services/ast_differ.rs, crates/samlang-core/src/services/gc.rs, crates/samlang-core/src/services/global_searcher.rs, crates/samlang-core/src/services/location_cover.rs, crates/samlang-core/src/services/variable_definition.rs, stdlib/utils.sam, tests/SortableList.sam
[ast][refactor] Move and rename some pattern AST nodes
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1051).
* #1056
* #1055
* #1054
* #1053
* #1052
* __->__ #1051
* #1050
=> [ast][refactor] Move and rename some pattern AST nodes

crates/samlang-core/src/common.rs, crates/samlang-core/src/printer/prettier.rs, crates/samlang-core/src/printer/source_printer.rs
[refactor] Move rc string to printer module
=> [refactor] Move rc string to printer module

crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/ssa_analysis.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/printer/source_printer.rs, crates/samlang-core/src/services/ast_differ.rs, crates/samlang-core/src/services/gc.rs, crates/samlang-core/src/services/location_cover.rs, crates/samlang-core/src/services/variable_definition.rs, std/list.sam, tests/AndOrInsideIf.sam, tests/DifferentExpressionDemo.sam
[lang] Support nested destructuring patterns
=> [lang] Support nested destructuring patterns

crates/samlang-core/src/checker.rs, crates/samlang-core/src/checker/pattern_matching.rs
[checker][pattern-matching] Core useful checker implementation
Implement the algorithm as described in http://moscova.inria.fr/~maranget/papers/warn/warn.pdf
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1065).
* #1068
* #1067
* #1066
* __->__ #1065
=> [checker][pattern-matching] Core useful checker implementation

crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs, crates/samlang-core/src/checker.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/pattern_matching.rs, crates/samlang-core/src/checker/ssa_analysis.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/services/variable_definition.rs
[ast][refactor] Rename and refactor pattern struct to prepare for later reuse
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1066).
* #1068
* #1067
* __->__ #1066
* #1065
=> [ast][refactor] Rename and refactor pattern struct to prepare for later reuse

crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs, crates/samlang-core/src/checker.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/pattern_matching.rs, crates/samlang-core/src/checker/ssa_analysis.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/services/variable_definition.rs
[ast] AST nodes for deeply nesting matching pattern
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1067).
* #1068
* __->__ #1067
* #1066
* #1065
=> [ast] AST nodes for deeply nesting matching pattern

packages/samlang-vscode/CHANGELOG.md, packages/samlang-vscode/package.json, packages/samlang-vscode/snippets.json, packages/samlang-vscode/syntaxes/samlang.json
[vscode] Publish new version of extension with new syntax support
=> [vscode] Publish new version of extension with new syntax support

.github/workflows/main.yml, .github/workflows/validate.yml, README.md, crates/samlang-cli/src/main.rs, crates/samlang-core/src/lib.rs, crates/samlang-core/src/loader.js, packages/samlang-cli/loader.d.ts
[ci] Reduce reliance on pnpm
pnpm is great, but I'd like to have all the CI jobs work without any installs, with the exception for website builds in the future.
=> [ci] Reduce reliance on pnpm

.github/workflows/main.yml, crates/samlang-wasm/test-samlang-wasm.mjs
[ci] Continue to build wasm with pnpm
=> [ci] Continue to build wasm with pnpm

packages/samlang-website/src/components/Demo.tsx
[website] Fix height calculation
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1074).
* #1076
* #1075
* __->__ #1074
=> [website] Fix height calculation

packages/samlang-website/package.json, packages/samlang-website/src/components/Demo.tsx, packages/samlang-website/src/components/samlang-config.ts
[website] Reduce initial load size
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1075).
* #1076
* __->__ #1075
* #1074
=> [website] Reduce initial load size

packages/samlang-vscode/.vscodeignore, packages/samlang-vscode/CHANGELOG.md, packages/samlang-vscode/package.json, packages/samlang-vscode/syntaxes/samlang.json
=> [vscode] Publish 0.0.15

.github/workflows/main.yml, .github/workflows/rust.yml, .github/workflows/website.yml
[ci] Add website build job on every push
=> [ci] Add website build job on every push

.github/workflows/main.yml, .github/workflows/release.yml, benchmark.sh, package.json
=> [ci] Add release workflow

.cargo/config.toml, .github/workflows/release.yml
[rust] Try fix release workflow
yolo
=> [rust] Try fix release workflow

.github/workflows/main.yml, .github/workflows/website.yml
[ci] Build and test wasm at CI time
=> [ci] Build and test wasm at CI time

.github/workflows/main.yml, .github/workflows/rust.yml, .github/workflows/website.yml, vercel.json
=> [ci] CD for samlang website

.github/workflows/main.yml, package.json, vercel.json
[ci] Try website deployment agian
=> [ci] Try website deployment agian

.github/workflows/main.yml, packages/samlang-website/src/app/page.tsx
[website] Update getting started section
=> [website] Update getting started section

packages/samlang-website/src/app/layout.tsx
[website] Fix Google Analytics
=> [website] Fix Google Analytics

crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs
[ast][source] Add util function to collect bindings from match pattern
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1098).
* #1100
* #1099
* __->__ #1098
=> [ast][source] Add util function to collect bindings from match pattern

crates/samlang-core/src/ast/hir.rs, crates/samlang-core/src/ast/hir_tests.rs, crates/samlang-core/src/ast/lir.rs, crates/samlang-core/src/ast/lir_tests.rs, crates/samlang-core/src/ast/mir.rs, crates/samlang-core/src/ast/mir_tests.rs, crates/samlang-core/src/compiler/lir_lowering.rs, crates/samlang-core/src/compiler/lir_unused_name_elimination.rs, crates/samlang-core/src/compiler/mir_constant_param_elimination.rs, crates/samlang-core/src/compiler/mir_generics_specialization.rs, crates/samlang-core/src/compiler/mir_type_deduplication.rs, crates/samlang-core/src/compiler/wasm_lowering.rs, crates/samlang-core/src/interpreter.rs, crates/samlang-core/src/optimization/common_subexpression_elimination.rs, crates/samlang-core/src/optimization/conditional_constant_propagation.rs, crates/samlang-core/src/optimization/conditional_constant_propagation_tests.rs, crates/samlang-core/src/optimization/dead_code_elimination.rs, crates/samlang-core/src/optimization/dead_code_elimination_tests.rs, crates/samlang-core/src/optimization/inlining.rs, crates/samlang-core/src/optimization/inlining_tests.rs, crates/samlang-core/src/optimization/local_value_numbering.rs, crates/samlang-core/src/optimization/local_value_numbering_tests.rs, crates/samlang-core/src/optimization/loop_induction_analysis.rs, crates/samlang-core/src/optimization/loop_induction_variable_elimination.rs, crates/samlang-core/src/optimization/loop_invariant_code_motion.rs, crates/samlang-core/src/optimization/unused_name_elimination.rs
[compiler] Add late init capability into IRs
=> [compiler] Add late init capability into IRs

.cargo/config.toml, .github/workflows/rust.yml, .github/workflows/website.yml
=> [ci] Use better rust cache

crates/samlang-core/src/ast/lir.rs, crates/samlang-core/src/ast/lir_tests.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/compiler/lir_lowering.rs
[compiler][hir] Create fresh bindings for conditionally destructured names
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1110).
* __->__ #1110
* #1109
=> [compiler][hir] Create fresh bindings for conditionally destructured names

crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs
[ast][hir] Add function that conversatively decide whether a matching pattern will always match
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1111).
* #1112
* __->__ #1111
=> [ast][hir] Add function that conversatively decide whether a matching pattern will always match

crates/samlang-core/src/optimization/conditional_constant_propagation.rs, crates/samlang-core/src/optimization/conditional_constant_propagation_tests.rs
[optimization] Optimize trivial if else returning bool literals
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1113).
* #1114
* __->__ #1113
=> [optimization] Optimize trivial if else returning bool literals

crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/optimization/conditional_constant_propagation.rs, crates/samlang-core/src/optimization/conditional_constant_propagation_tests.rs, tests/DifferentModulesDemo.sam
[compiler][hir] Compiler support for if let destructuring
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1114).
* __->__ #1114
* #1113
=> [compiler][hir] Compiler support for if let destructuring

crates/samlang-core/src/errors.rs
[errors] Add new error kinds to prepare for deeply nested pattern matching
=> [errors] Add new error kinds to prepare for deeply nested pattern matching

crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/services/global_searcher.rs, crates/samlang-core/src/services/location_cover.rs, tests/DifferentExpressionDemo.sam
[checker] Exhausive binding check
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1119).
* #1120
* __->__ #1119
=> [checker] Exhausive binding check

crates/samlang-core/src/ast/source.rs, crates/samlang-core/src/ast/source_tests.rs, crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/ssa_analysis.rs, crates/samlang-core/src/compiler/hir_lowering.rs, crates/samlang-core/src/optimization/conditional_constant_propagation.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/printer/source_printer.rs, crates/samlang-core/src/services/api_tests.rs, crates/samlang-core/src/services/ast_differ.rs, crates/samlang-core/src/services/gc.rs, crates/samlang-core/src/services/global_searcher.rs, crates/samlang-core/src/services/location_cover.rs, crates/samlang-core/src/services/variable_definition.rs
[parser][checker][compiler] Unify implementation of matching and destructuring pattern
=> [parser][checker][compiler] Unify implementation of matching and destructuring pattern

crates/samlang-core/src/parser/source_parser.rs
[parser] Fix location of import statement
Also fixed the issue that auto import inserts import statement in the wrong place.
=> [parser] Fix location of import statement

crates/samlang-core/src/ast/loc.rs
[ast][cleanup][EZ] Remove unused type
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1128).
* #1129
* __->__ #1128
=> [ast][cleanup][EZ] Remove unused type

Cargo.lock, Cargo.toml, crates/samlang-core/Cargo.toml, crates/samlang-core/src/checker.rs, crates/samlang-core/src/checker/checker_tests.rs, crates/samlang-core/src/checker/global_signature.rs, crates/samlang-core/src/checker/main_checker.rs, crates/samlang-core/src/checker/ssa_analysis.rs, crates/samlang-core/src/checker/ssa_analysis_tests.rs, crates/samlang-core/src/checker/type_system.rs, crates/samlang-core/src/checker/typing_context.rs, crates/samlang-core/src/checker/typing_context_tests.rs, crates/samlang-core/src/integration_tests.rs, crates/samlang-core/src/lib.rs, crates/samlang-core/src/parser.rs, crates/samlang-core/src/parser/lexer.rs, crates/samlang-core/src/parser/lexer_test.rs, crates/samlang-core/src/parser/source_parser.rs, crates/samlang-core/src/printer/source_printer.rs, crates/samlang-core/src/services/api.rs, crates/samlang-core/src/services/ast_differ.rs, crates/samlang-core/src/services/dep_graph.rs, crates/samlang-core/src/services/gc.rs, crates/samlang-core/src/services/global_searcher.rs, crates/samlang-core/src/services/location_cover.rs, crates/samlang-core/src/services/server_state.rs, crates/samlang-core/src/services/variable_definition.rs, crates/samlang-errors/Cargo.toml, crates/samlang-errors/src/lib.rs
[repo] Split errors into another crate
=> [repo] Split errors into another crate

crates/samlang-core/src/integration_tests.rs, crates/samlang-parser/src/lib.rs, crates/samlang-parser/src/source_parser.rs, crates/samlang-printer/src/source_printer.rs, crates/samlang-services/src/global_searcher.rs, crates/samlang-services/src/location_cover.rs, std/list.sam, std/map.sam, std/option.sam, std/result.sam, tests/SortableList.sam
[parser] More restrictive parsing for match pattern separators
=> [parser] More restrictive parsing for match pattern separators

crates/samlang-checker/src/typing_context.rs
[checker] Fix private class method resolution
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1142).
* #1143
* __->__ #1142
=> [checker] Fix private class method resolution

crates/samlang-ast/src/hir_tests.rs, crates/samlang-ast/src/lir_tests.rs, crates/samlang-ast/src/loc.rs, crates/samlang-ast/src/mir_tests.rs, crates/samlang-ast/src/reason.rs, crates/samlang-ast/src/source_tests.rs, crates/samlang-checker/src/pattern_matching.rs, crates/samlang-checker/src/ssa_analysis_tests.rs, crates/samlang-checker/src/type_.rs, crates/samlang-checker/src/type_system.rs, crates/samlang-checker/src/typing_context_tests.rs, crates/samlang-cli/src/configuration.rs, crates/samlang-cli/src/logo.rs, crates/samlang-compiler/src/mir_constant_param_elimination.rs, crates/samlang-errors/src/lib.rs, crates/samlang-heap/src/lib.rs, crates/samlang-optimization/src/loop_induction_analysis.rs, crates/samlang-optimization/src/optimization_common.rs, crates/samlang-parser/src/lexer.rs, crates/samlang-parser/src/lib.rs, crates/samlang-printer/src/prettier.rs, crates/samlang-services/src/api_tests.rs, crates/samlang-services/src/ast_differ.rs, crates/samlang-services/src/variable_definition.rs
[repo] Tweak tests to keep 100% coverage after Rust 1.74
=> [repo] Tweak tests to keep 100% coverage after Rust 1.74

Cargo.lock, crates/samlang-ast/Cargo.toml, crates/samlang-checker/Cargo.toml, crates/samlang-compiler/Cargo.toml, crates/samlang-core/Cargo.toml, crates/samlang-errors/Cargo.toml, crates/samlang-heap/Cargo.toml, crates/samlang-optimization/Cargo.toml, crates/samlang-parser/Cargo.toml, crates/samlang-parser/src/lib.rs, crates/samlang-printer/Cargo.toml, crates/samlang-services/Cargo.toml, std/boxed.sam, std/interfaces.sam, std/map.sam, tests/AllTests.sam, tests/MapTests.sam, tests/SortableList.sam, tests/StdLib.sam, tests/snapshot.txt
[stdlib] Finish implementation of builtin Map class
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1147).
* __->__ #1147
* #1146
=> [stdlib] Finish implementation of builtin Map class

Cargo.lock, crates/samlang-cli/Cargo.toml, crates/samlang-cli/src/main.rs, crates/samlang-core/Cargo.toml, crates/samlang-core/src/lib.rs
[repo] Move core formatting logic into CLI
=> [repo] Move core formatting logic into CLI

crates/samlang-compiler/src/hir_lowering.rs
[compiler][hir] Add missing nested synthetic lambdas
=> [compiler][hir] Add missing nested synthetic lambdas

tests/MapTests.sam
=> [tests] More tests on map

crates/samlang-checker/src/pattern_matching.rs, crates/samlang-heap/src/lib.rs
[debug] Better debug printing for some structures
=> [debug] Better debug printing for some structures

crates/samlang-ast/src/mir.rs, crates/samlang-ast/src/wasm.rs, crates/samlang-checker/src/pattern_matching.rs, crates/samlang-compiler/src/hir_lowering.rs, crates/samlang-compiler/src/hir_string_manager.rs, crates/samlang-compiler/src/lir_lowering.rs, crates/samlang-compiler/src/mir_constant_param_elimination.rs, crates/samlang-compiler/src/mir_generics_specialization.rs, crates/samlang-compiler/src/wasm_lowering.rs
[checker][pattern] Remove too strict validation
This assumption will not hold on invalid patterns.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1160).
* #1163
* #1162
* #1161
* __->__ #1160
* #1159
=> [checker][pattern] Remove too strict validation

crates/samlang-ast/src/mir.rs, crates/samlang-ast/src/wasm.rs, crates/samlang-checker/src/pattern_matching.rs, crates/samlang-compiler/src/hir_lowering.rs, crates/samlang-compiler/src/hir_string_manager.rs, crates/samlang-compiler/src/lir_lowering.rs, crates/samlang-compiler/src/mir_constant_param_elimination.rs, crates/samlang-compiler/src/mir_generics_specialization.rs, crates/samlang-compiler/src/wasm_lowering.rs, packages/samlang-website/src/components/samlang-wasm-glue.js, std/set.sam, tests/AllTests.sam, tests/MapTests.sam, tests/SetTests.sam, tests/snapshot.txt
[stdlib] Set support
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1161).
* #1163
* #1162
* __->__ #1161
* #1160
* #1159
=> [stdlib] Set support

crates/samlang-ast/src/mir.rs, crates/samlang-ast/src/wasm.rs, crates/samlang-checker/src/pattern_matching.rs, crates/samlang-compiler/src/hir_lowering.rs, crates/samlang-compiler/src/hir_string_manager.rs, crates/samlang-compiler/src/lir_lowering.rs, crates/samlang-compiler/src/mir_constant_param_elimination.rs, crates/samlang-compiler/src/mir_generics_specialization.rs, crates/samlang-compiler/src/wasm_lowering.rs, crates/samlang-services/src/location_cover.rs, packages/samlang-website/src/components/samlang-wasm-glue.js, std/set.sam, tests/AllTests.sam, tests/MapTests.sam, tests/SetTests.sam, tests/snapshot.txt
[ide][hover] Collect unannotated lambda params as typed name
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1162).
* #1163
* __->__ #1162
* #1161
* #1160
* #1159
=> [ide][hover] Collect unannotated lambda params as typed name

crates/samlang-ast/src/source.rs, crates/samlang-ast/src/source_tests.rs, crates/samlang-checker/src/global_signature.rs, crates/samlang-checker/src/main_checker.rs, crates/samlang-checker/src/ssa_analysis.rs, crates/samlang-checker/src/type_.rs, crates/samlang-compiler/src/hir_lowering.rs, crates/samlang-parser/src/source_parser.rs, crates/samlang-printer/src/lib.rs, crates/samlang-printer/src/prettier.rs, crates/samlang-printer/src/source_printer.rs, crates/samlang-services/src/ast_differ.rs, crates/samlang-services/src/gc.rs, crates/samlang-services/src/global_searcher.rs, crates/samlang-services/src/variable_definition.rs
[parser][printer] Consistent comment attachment and printing for types
=> [parser][printer] Consistent comment attachment and printing for types

crates/samlang-ast/src/source.rs, crates/samlang-ast/src/source_tests.rs, crates/samlang-checker/src/main_checker.rs, crates/samlang-checker/src/ssa_analysis.rs, crates/samlang-compiler/src/hir_lowering.rs, crates/samlang-parser/src/source_parser.rs, crates/samlang-printer/src/source_printer.rs, crates/samlang-services/src/gc.rs, crates/samlang-services/src/global_searcher.rs, crates/samlang-services/src/location_cover.rs, crates/samlang-services/src/variable_definition.rs
[parser][printer] Consistent comment attachment and printing for patterns
=> [parser][printer] Consistent comment attachment and printing for patterns

crates/samlang-ast/src/source.rs, crates/samlang-ast/src/source_tests.rs, crates/samlang-checker/src/checker_tests.rs, crates/samlang-checker/src/global_signature.rs, crates/samlang-checker/src/main_checker.rs, crates/samlang-checker/src/ssa_analysis.rs, crates/samlang-checker/src/ssa_analysis_tests.rs, crates/samlang-checker/src/type_.rs, crates/samlang-compiler/src/hir_lowering.rs, crates/samlang-parser/src/lib.rs, crates/samlang-parser/src/source_parser.rs, crates/samlang-printer/src/source_printer.rs, crates/samlang-services/src/gc.rs, crates/samlang-services/src/global_searcher.rs, crates/samlang-services/src/lib.rs, crates/samlang-services/src/location_cover.rs, crates/samlang-services/src/variable_definition.rs
[parser][printer] Consistent comment attachment and printing for expressions
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1167).
* #1170
* #1169
* #1168
* __->__ #1167
=> [parser][printer] Consistent comment attachment and printing for expressions

crates/samlang-ast/src/source.rs, crates/samlang-ast/src/source_tests.rs, crates/samlang-parser/src/lexer.rs, crates/samlang-parser/src/source_parser.rs, crates/samlang-printer/src/lib.rs, crates/samlang-printer/src/source_printer.rs, crates/samlang-services/src/ast_differ.rs, crates/samlang-services/src/lib.rs
[lexer] Remove unnecessary EOF struct
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1170).
* __->__ #1170
* #1169
=> [lexer] Remove unnecessary EOF struct

crates/samlang-heap/src/lib.rs, crates/samlang-optimization/src/loop_induction_analysis.rs
[repo] Fix lints after upgrading to Rust 1.75
=> [repo] Fix lints after upgrading to Rust 1.75

crates/samlang-services/src/location_cover.rs
[ide] Search type annotations and parameters
=> [ide] Search type annotations and parameters

crates/samlang-checker/src/main_checker.rs, crates/samlang-checker/src/ssa_analysis.rs, crates/samlang-parser/src/source_parser.rs, crates/samlang-printer/src/source_printer.rs, crates/samlang-services/src/gc.rs, crates/samlang-services/src/global_searcher.rs, crates/samlang-services/src/location_cover.rs, crates/samlang-services/src/variable_definition.rs
[refactor] Factor out block functions
=> [refactor] Factor out block functions

crates/samlang-ast/src/source.rs, crates/samlang-printer/src/prettier.rs, crates/samlang-printer/src/source_printer.rs
[printer] Avoid allocating static string
=> [printer] Avoid allocating static string

packages/samlang-website/src/components/Demo.tsx
[web][demo] Warn against lack of WASM GC
=> [web][demo] Warn against lack of WASM GC

crates/samlang-wasm/samlang-wasm.test.mjs, crates/samlang-wasm/setup-generated-package.sh
Bun randomly segfaults, and I give up...
=> [wasm][test] Stop depend on bun specific test

crates/samlang-ast/src/lib.rs
[ast] Document various IRs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1186).
* #1188
* #1187
* __->__ #1186
=> [ast] Document various IRs

crates/samlang-ast/src/hir.rs, crates/samlang-ast/src/hir_tests.rs, crates/samlang-ast/src/lib.rs, crates/samlang-compiler/src/mir_generics_specialization.rs
[ast][hir] Remove unused nodes
They are never constructed.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1188).
* __->__ #1188
* #1187
* #1186
=> [ast][hir] Remove unused nodes

crates/samlang-ast/src/hir.rs, crates/samlang-ast/src/hir_tests.rs, crates/samlang-ast/src/mir_tests.rs, crates/samlang-checker/src/type_.rs, crates/samlang-printer/src/prettier.rs, crates/samlang-printer/src/source_printer.rs, crates/samlang-services/src/lib.rs, crates/samlang-services/src/location_cover.rs
[chore] Address lints and coverage after latest rust upgrade
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1191).
* #1190
* __->__ #1191
=> [chore] Address lints and coverage after latest rust upgrade

crates/samlang-ast/src/mir.rs, crates/samlang-ast/src/mir_tests.rs, crates/samlang-compiler/src/lir_lowering.rs, crates/samlang-compiler/src/mir_generics_specialization.rs, crates/samlang-compiler/src/mir_type_deduplication.rs
[ast][mir] Int -> Int32
Summary:
Test Plan:
=> [ast][mir] Int -> Int32

crates/samlang-ast/src/lir.rs, crates/samlang-ast/src/lir_tests.rs, crates/samlang-ast/src/mir.rs, crates/samlang-ast/src/mir_tests.rs, crates/samlang-compiler/src/lir_lowering.rs, crates/samlang-compiler/src/lir_unused_name_elimination.rs, crates/samlang-compiler/src/mir_constant_param_elimination.rs, crates/samlang-compiler/src/mir_tail_recursion_rewrite.rs, crates/samlang-compiler/src/mir_type_deduplication.rs, crates/samlang-compiler/src/wasm_lowering.rs, crates/samlang-optimization/src/conditional_constant_propagation.rs, crates/samlang-optimization/src/loop_induction_analysis.rs, crates/samlang-optimization/src/unused_name_elimination.rs
[ast][ir] Introduce i31 values in MIR and LIR
=> [ast][ir] Introduce i31 values in MIR and LIR

crates/samlang-ast/src/hir.rs, crates/samlang-ast/src/hir_tests.rs, crates/samlang-ast/src/lir.rs, crates/samlang-ast/src/lir_tests.rs, crates/samlang-ast/src/mir.rs, crates/samlang-ast/src/mir_tests.rs, crates/samlang-compiler/src/hir_lowering.rs, crates/samlang-compiler/src/lir_lowering.rs, crates/samlang-compiler/src/lir_unused_name_elimination.rs, crates/samlang-compiler/src/mir_constant_param_elimination.rs, crates/samlang-compiler/src/mir_generics_specialization.rs, crates/samlang-compiler/src/mir_type_deduplication.rs, crates/samlang-compiler/src/wasm_lowering.rs, crates/samlang-optimization/src/common_subexpression_elimination.rs, crates/samlang-optimization/src/conditional_constant_propagation.rs, crates/samlang-optimization/src/conditional_constant_propagation_tests.rs, crates/samlang-optimization/src/dead_code_elimination.rs, crates/samlang-optimization/src/dead_code_elimination_tests.rs, crates/samlang-optimization/src/inlining.rs, crates/samlang-optimization/src/inlining_tests.rs, crates/samlang-optimization/src/local_value_numbering.rs, crates/samlang-optimization/src/local_value_numbering_tests.rs, crates/samlang-optimization/src/loop_induction_analysis.rs, crates/samlang-optimization/src/loop_induction_variable_elimination.rs, crates/samlang-optimization/src/loop_invariant_code_motion.rs, crates/samlang-optimization/src/optimization_common.rs, crates/samlang-optimization/src/unused_name_elimination.rs
[ir] Split Unary statement
We will need to attach extra information to the IsPointer instruction.
=> [ir] Split Unary statement

crates/samlang-ast/src/hir.rs
[hir] Delete unused UnaryOperator
=> [hir] Delete unused UnaryOperator

crates/samlang-compiler/src/hir_lowering.rs, crates/samlang-compiler/src/lir_lowering.rs
[compiler] Use i31 zero to model class id
Summary:
Test Plan:
=> [compiler] Use i31 zero to model class id

Cargo.lock, crates/samlang-compiler/Cargo.toml
=> [dependency] Bump wat and include wast

crates/samlang-ast/src/wasm.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/SamChou19815/samlang/pull/1236).
* #1237
* __->__ #1236
=> [wasm][ast] Support relevant `struct.*` instructions

packages/samlang-website/src/components/samlang-programs.ts
=> [website] Adjust pattern order

crates/samlang-checker/src/type_system.rs
=> [chore] Make use of chained if

crates/samlang-ast/src/source.rs, crates/samlang-checker/src/main_checker.rs, crates/samlang-checker/src/ssa_analysis.rs, crates/samlang-checker/src/type_system.rs, crates/samlang-cli/src/main.rs, crates/samlang-optimization/src/conditional_constant_propagation.rs, crates/samlang-optimization/src/loop_induction_analysis.rs, crates/samlang-parser/src/lexer.rs, crates/samlang-parser/src/source_parser.rs, crates/samlang-printer/src/source_printer.rs, crates/samlang-services/src/dep_graph.rs, crates/samlang-services/src/lib.rs, crates/samlang-services/src/location_cover.rs
=> [chore] Upgrade to rust 1.89

crates/samlang-cli/src/main.rs, crates/samlang-optimization/src/loop_induction_analysis.rs
=> [chore] Simplify more if let blocks

Cargo.lock, crates/samlang-optimization/Cargo.toml
=> [dependency] Remove unused dependency
